### PR TITLE
Ensure using `@defer` or `@stream` with `fetchMore` rerenders with incremental results

### LINKED ISSUE #11034: `fetchMore` does not incrementally update when using a query with `@defer`
### Issue Description

When working a query that uses `@defer`, calling `fetchMore` to get additional paginated results does not incrementally update the observable until the result has been completely loaded. I would have expected to see incremental results from `fetchMore`.

### Link to Reproduction

See [this change](https://github.com/apollographql/apollo-client/commit/5bc220bb80fe8b202844ef94785748c234ab8ad4#diff-859c717a9aadba976d9ad09f6c45546ffa1ecde2c0326ac24b9b460dd8769050) for the expected behavior

### Reproduction Steps

See the linked change and the comments there

### PR DESCRIPTION
**Pull request by jerelmiller**
Fixes #11034

Ensures `fetchMore` will rerender incremental results from `@defer` and `@stream`.

### CODE REVIEW

File: src/core/ObservableQuery.ts [hunk 1]
```diff
@@ -885,115 +893,190 @@ Did you mean to call refetch(variables) instead of refetch({ variables })?`,
...
-              // will be overwritten anyways, just here for types sake
-              loading: false,
-              data: data as any,
-              dataState:
-                lastResult.dataState === "streaming" ? "streaming" : "complete",
-            },
-            source: "network",
-          });
+    const { promise, operator } = getTrackingOperatorPromise(
+      (value: QueryNotification.Value<TFetchData>) => {
```
Comment (phryneas) [inline src/core/ObservableQuery.ts:898]: This is equivalent to the `filterMapCb` in the other `getTrackingOperatorPromise` usage - could you extract that into a function on module level?

File: src/core/ObservableQuery.ts [hunk 2]
```diff
@@ -885,115 +893,190 @@ Did you mean to call refetch(variables) instead of refetch({ variables })?`,
...
+        },
       });
+
+    return preventUnhandledRejection(
+      promise
+        .then((result) => toQueryResult(this.maskResult(result)))
+        .finally(() => {
+          subscription.unsubscribe();
+          if (isCached && !wasUpdated) {
+            finalize();
```
Comment (phryneas) [inline src/core/ObservableQuery.ts:1053]: I think `finalize` here could be called unconditionally - calling it more than once is inconsequential, and we want it to definitely be called at least once.

File: src/core/ObservableQuery.ts [hunk 3]
```diff
@@ -885,115 +893,190 @@ Did you mean to call refetch(variables) instead of refetch({ variables })?`,
...
+
+            const lastResult = this.getCurrentResult();
+
+            if (lastResult.networkStatus === NetworkStatus.streaming) {
```
Comment (phryneas) [inline src/core/ObservableQuery.ts:1057]: This branch shouldn't be necessary for `networkStatus`, but *maybe* for `dataState`... Could you check for `lastResult.dataState` instead of `networkStatus`?
