### PR TITLE
prevent merging into supertype field policies

### LINKED ISSUE #12749: For `typePolicies` super-type field policy will be overriden by child type field policy
### Issue Description

When using `InMemoryCache` with `typePolicies` and `possibleTypes`, if field policies with same field name are defined in both super-type and child type, super-type field policy will be overriden by child field policy.

### Link to Reproduction

https://github.com/jet2jet/react-apollo-error-type-policies

### Reproduction Steps

When `npm run start` and open http://localhost:3000, All 'Person name' data are capitalized (capitalization is defined for 'Address name' field policy, not for 'All__' field policy)

### `@apollo/client` version

3.11.4

### PR DESCRIPTION
**Pull request by phryneas**
Fixes #12749

### CODE REVIEW

File: src/cache/inmemory/policies.ts [hunk 1]
```diff
@@ -632,21 +653,10 @@ export class Policies {
 
   private getFieldPolicy(
     typename: string | undefined,
-    fieldName: string,
-    createIfMissing: boolean
```
Comment (phryneas) [inline src/cache/inmemory/policies.ts:636]: `createIfMissing: true` was only passed in once, and with these changes it made more sense to solve this a different way, so I inlined that case there and modified it a bit.

File: .size-limits.json [hunk 2]
```diff
@@ -1,4 +1,3 @@
 {
-  "dist/apollo-client.min.cjs": 42398,
-  "import { ApolloClient, InMemoryCache, HttpLink } from \"@apollo/client\" (production)": 34595
```
Comment (jerelmiller) [inline .size-limits.json]: Was this line removed by accident?

**Review by jerelmiller — APPROVED** [review]
💯
