### PR TITLE
Fix `client.query` using `defaultOptions.watchQuery`

### LINKED ISSUE #13136: `client.query` uses `defaultOptions.watchQuery`
> Hi @jerelmiller ,
> Yes, I meant `client.query` (this is the terminology used in the [docs](https://www.apollographql.com/docs/react/data/error-handling#error-handling-across-api-types)).
> In our app, we have the following default options:
> ```ts
>   defaultOptions: {
>     watchQuery: {
>       errorPolicy: 'all',
>       fetchPolicy: 'network-only',
>       nextFetchPolicy: 'cache-first',
>     },
>   },
> ```
> notice we don't configure `query` default options, only `watchQuery`.
> 
> So when we call `client.query`, and an error returns,  the promise is not rejected (`all` behavior, even though the default should be `none`), but if we change the above options to `none`, it does get rejected. so it seems that `watchQuery` default options, affect the promised base api for some reason.
> I suspect that also happens to `fetchPolicy`, but didn't check that.
> 
> To be honest, not sure what's the use case for separate default options for `watchQuery` and `query`, it might make more sense to have default options for both promise based and observable based.  

 _Originally posted by @ItaiYosephi in [#13123](https://github.com/apollographql/apollo-client/issues/13123#issuecomment-3851577766)_

### PR DESCRIPTION
**Pull request by jerelmiller**
Fixes #13136

### CODE REVIEW

File: src/core/QueryManager.ts [hunk 1]
```diff
@@ -1185,10 +1185,9 @@ export class QueryManager {
   ): ObservableAndInfo<TData> {
     const variables = this.getVariables(query, options.variables) as TVariables;
 
-    const defaults = this.defaultOptions.watchQuery;
```
Comment (jerelmiller) [inline src/core/QueryManager.ts:1188]: Will need to dig a bit deeper on this to determine how this affects `client.refetchQueries` when objects are provided. This may changes those use cases.

Comment (jerelmiller) [reply src/core/QueryManager.ts:1188]: Looks like it did, though its only supported through mutations.

To avoid a breaking change, I've reapplied defaultOptions in this case [72e8ece](https://github.com/apollographql/apollo-client/pull/13135/commits/72e8ecebfc9f55e2e889a008e59a008ef2c8fae0)

**Review by phryneas — APPROVED** [review]
