### PR TITLE
Fix `fetchMore` for queries with `no-cache` fetch policies

### LINKED ISSUE #11965: fetchMore with fetchPolicy: "no-cache" makes two requests
### Issue Description

fetchMore useQuery with fetchPolicy: "no-cache" just makes two requests. One with variables and the second request is with default variables. I can't post a link to reproduction, the requests are visible on the backend. NextJS 14.2 dev mode.

### Link to Reproduction

-

### Reproduction Steps

`  const { loading, fetchMore } = useQuery(GET_MESSAGES, {
    fetchPolicy: "no-cache",
    onCompleted: handleCompleted,
    onError: handleError,
    variables: {
      slug: params.slug,
    },
  });`

### `@apollo/client` version

3.10.8

### PR DESCRIPTION
**Pull request by jerelmiller**
Fixes #11965

This fixes several issues when using `fetchMore` with `no-cache` queries.

* Ensures we don't run multiple network requests unnecessarily
* Does not write the `fetchMore` result to the cache
* Ensures the component is re-rendered using the result of the `updateQuery` function.

**Important**

This PR updates `fetchMore` to force the user to provide an `updateQuery` function when using a query with a `no-cache` fetch policy. Without this, there is no way for the user to determine how to merge the result with the current query data since other mechanisms rely on the cache to perform this functionality. Calling `fetchMore` without an `updateQuery` function will now throw.

### CODE REVIEW

File: src/core/ObservableQuery.ts [hunk 1]
```diff
@@ -484,6 +484,15 @@ Did you mean to call refetch(variables) instead of refetch({ variables })?`,
 
     const updatedQuerySet = new Set<DocumentNode>();
 
+    const updateQuery = fetchMoreOptions?.updateQuery;
+
+    if (this.options.fetchPolicy === "no-cache") {
```
Comment (jerelmiller) [inline src/core/ObservableQuery.ts:489]: The more I think about this, I'm not actually sure we need to enforce this. I think a reasonable default could be just to use the `fetchMore` result if `updateQuery` is not provided.

That being said, `fetchMore` _does_ give you the opportunity to provide a different `query` that can be used to fetch only the paginated fields and avoid refetching a bunch of extra data. We _could_ leave this check in but change it to enforce an `updateQuery` function only if a custom `query` is provided when used with a `no-cache` fetch policy

Comment (jerelmiller) [reply src/core/ObservableQuery.ts:489]: I'm also willing to fully admit that `updateQuery` may be the wrong approach here. Per [this comment](https://github.com/apollographql/apollo-client/issues/8915#issuecomment-1133021058) the cache is meant to play a big role in updating paginated results. This PR hijacks this a bit as the mechanism to merge the results.

That being said, the name `updateQuery` is still accurate here as we are using it to update the result of your query so that we can emit and store the result. From an outsider perspective, this seems to jive well together.

File: .changeset/nice-worms-juggle.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@apollo/client": patch
+---
+
+Fix issue where `fetchMore` would write it's result data to the cache when using it with a `no-cache` fetch policy.
```
Comment (phryneas) [inline .changeset/nice-worms-juggle.md:5]:
```suggestion
Fix an issue where `fetchMore` would write its result data to the cache when using it with a `no-cache` fetch policy.
```

File: src/core/ObservableQuery.ts (hunk 1 above)
Comment (phryneas) [reply src/core/ObservableQuery.ts:489]: I would enforce this - people might expect `typePolicies` to take over otherwise, despite them being a cache feature.

File: src/core/ObservableQuery.ts [hunk 3]
```diff
@@ -493,48 +502,65 @@ Did you mean to call refetch(variables) instead of refetch({ variables })?`,
...
-              cache.writeQuery({
-                query: combinedOptions.query,
-                variables: combinedOptions.variables,
-                data: fetchMoreResult.data,
-              });
-            }
-          },
+        if (this.options.fetchPolicy === "no-cache") {
+          const lastResult = this.getLast("result")!;
+          const data = updateQuery!(lastResult.data, {
```
Comment (phryneas) [inline src/core/ObservableQuery.ts:507]: Are we concerned about race conditions of any kind?
E.g. calling `fetchMore` immediately, before the initial request finished - what do we do when `lastResult.data` comes in `undefined` here? Will that other result overwrite this completely? Would `loading: false` and `networkStatus: NetworkStatus.ready` be correct in such a situation?

**Review by phryneas — COMMENTED** [review]
This looks good, but also some questions seem more prevalent with `no-cache` than they seem with a cache. Do we have good answers for those?

File: .changeset/pink-horses-pay.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+"@apollo/client": patch
+---
+
+Fix issue where executing `fetchMore` with a `no-cache` fetch policy could sometimes result in multiple network requests.
```
Comment (jerelmiller) [inline .changeset/pink-horses-pay.md:5]:
```suggestion
Fix an issue where executing `fetchMore` with a `no-cache` fetch policy could sometimes result in multiple network requests.
```

File: src/core/ObservableQuery.ts (hunk 3 above)
Comment (jerelmiller) [reply src/core/ObservableQuery.ts]: Discuss in person. We decided to avoid setting anything other than `data` in the result.

File: src/core/ObservableQuery.ts (hunk 1 above)
Comment (jerelmiller) [reply src/core/ObservableQuery.ts]: Good call! I'll leave this as-is then. Thanks!

File: docs/source/pagination/core-api.mdx [hunk 5]
```diff
@@ -218,6 +218,41 @@ const cache = new InMemoryCache({
 
 This logic handles sequential page writes the same way the single-line strategy does, but it can also tolerate repeated, overlapping, or out-of-order writes, without duplicating any list items.
 
+### Updating the query with the fetch more result
```
Comment (jerelmiller) [inline docs/source/pagination/core-api.mdx:221]: I'm not 100% convinced this is accurate, especially since the previous techniques also "update the query". Ideas welcome on changing this headline.

**Review by phryneas — APPROVED** [review]
Looks good to me, everything else is doc-shedding :)

**Comment by jerelmiller** [comment]
Made one more tweak to the docs. I'll go ahead and merge this now to get the fix in place. I can make any additional docs tweaks in a separate PR if I get more feedback here.
