### PR TITLE
`prioritizeCacheValues` and `prerenderStatic`-related fixes

### LINKED ISSUE #13102: loading state always true when ssrForceFetchDelay is used
### Issue Description

I am seeing a weird issue with `@apollo/client` 4.x.
I use SSR in my project, I have a query that has the `skip` option set to `true`.
The `loading` state always stays to `true` and should be `false` since `skip` is used.
I even tried with `skipToken` and the same issue occurs.

I was able to isolate the issue to the following.
If I remove `ssrForceFetchDelay`, it seems to work (only for the client-side), it still starts as loading `true` while it should be `false` to begin with.

### Link to Reproduction

https://stackblitz.com/edit/cv9aq6f6-atoqurzf?file=pages%2Findex%2F%2BPage.tsx

### Reproduction Steps

I have done a small reproduction here to show the issue: https://stackblitz.com/edit/cv9aq6f6-atoqurzf?file=pages%2Findex%2F%2BPage.tsx (4.0.13)

Here is an example with 3.11.8 which works fine as intended: https://stackblitz.com/edit/cv9aq6f6-14sm35vq?file=pages%2Findex%2F%2BPage.tsx (3.11.8)

### `@apollo/client` version

4.0.13

### PR DESCRIPTION
**Pull request by phryneas**
Fixes #13102 and a few other findings I had along the way. It also adds a bunch of tests for these and related scenarios.

### CODE REVIEW

File: src/core/__tests__/ObservableQuery.ts [hunk 1]
```diff
@@ -5431,6 +5431,340 @@ describe("ObservableQuery", () => {
...
+          },
+        ],
+        expectedFetchCount: 0,
+      },
+    ])(
+      "fetchPolicy: '$fetchPolicy' with prioritizeCacheValues (cache populated: $populateCache)",
+      async ({
+        populateCache,
+        fetchPolicy,
+        expectedResult,
```
Comment (jerelmiller) [inline src/core/__tests__/ObservableQuery.ts]:
```suggestion
        expectedInitialCurrentResult,
```

Would it be possible to rename this as such to really clarify the purpose of this value? Reading through this the first time, I expected this to be the value checked as the final result after all emits. This would help clarify the intent.

Comment (phryneas) [reply src/core/__tests__/ObservableQuery.ts]: [`0323694` (this PR)](https://github.com/apollographql/apollo-client/pull/13105/commits/032369437331691c464b5bd49d7695bbf7761622)
