### PR TITLE
fix: error when server throws and we are also querying for a local field 

### LINKED ISSUE #10345: Querying a field that is required but fails throws inside apollo client
Hello.

I've encountered an issue that I thought was related to the apollo server - but after opening (https://github.com/apollographql/apollo-server/issues/7235) it appears that the issue is actually on the client.

It stems from the fact that the response object from the server differs when the field is required and not when the resolver throws.

This is the response when the field is required
```
{
  errors: [
    {
      message: 'something went wrong',
      locations: [Array],
      path: [Array],
      extensions: [Object]
    }
  ],
  data: null
}
```

This is the response when the field is not required
```
{
  errors: [
    {
      message: 'something went wrong',
      locations: [Array],
      path: [Array],
      extensions: [Object]
    }
  ],
  data: { willFailFieldIsNotRequired: null }
}
```

However the apollo client attempts to read the field from the data object regardless of whether or not the field is required. causing it to throw unexpectedly when the field is required

**Intended outcome:**
Attempting to query a field that is required but the resolver throws - I expected apollo client to function as usually

**Actual outcome:**
the client throws ```null is not an object (evaluating 'rootValue[aliasedFieldName]')``` because it is attempting to read the query name from the root object. 

**How to reproduce the issue:**
Refer to https://github.com/apollographql/apollo-server/issues/7235

**Versions**
System:
    OS: macOS 12.6
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Safari: 16.0
  npmPackages:
    @apollo/rover: ^0.7.0 => 0.7.0 
    @apollo/server: ^4.1.1 => 4.1.1 
    @apollo/client: ^3.6.10

### PR DESCRIPTION
**Pull request by mccraveiro**
closes #10345

### CODE REVIEW

**Comment by jerelmiller** [comment]
Hey @mccraveiro 👋 ! Thanks for your contribution and your patience!

I'd like to take a bit more time to understand the root issue here, and when I do, I'd be happy to provide a review. It's very likely your fix is the correct one here.

Just as an FYI, with the holidays coming up, I can't guarantee I'll be able to review this before the New Year as I've got a few commits I'm working on. I'll keep it on my radar though to come back to it as soon as I can!

File: src/__tests__/local-state/general.ts [hunk 1]
```diff
@@ -1196,4 +1196,45 @@ describe('Combining client and server state/operations', () => {
...
+        user {
+          firstName @client
+          lastName
+        }
+      }
+    `;
+
+    const cache = new InMemoryCache();
+    const link = new ApolloLink(operation => {
+      expect(operation.operationName).toBe('GetUser');
```
Comment (jerelmiller) [inline src/__tests__/local-state/general.ts:1212]:
```suggestion
```

Since this test is focused on checking that local resolvers are handled correctly when parent fields are null, I don't think we need this extra expectation. Let's omit it to reduce noise in the test.

File: src/__tests__/local-state/general.ts [hunk 2]
```diff
@@ -1196,4 +1196,45 @@ describe('Combining client and server state/operations', () => {
       },
     });
   });
+
+  itAsync('should handle server errors when field is required', (resolve, reject) => {
```
Comment (jerelmiller) [inline src/__tests__/local-state/general.ts:1200]: I'm not quite sold on the description here. While I get the reason behind this, I'd like to be a bit more specific about when this situation arises. 

I'm understanding the exception to be thrown when the root `data` property returns null. In cases where partial data is returned, local resolvers work as expected. Perhaps we could update this to something like:

```suggestion
  itAsync('handles server errors when root data property is null', (resolve, reject) => {
```

Feel free to wordsmith this a bit more, but I think something like this better captures the scenario we are testing. There are a variety of reasons the server might return `null` for the root `data` field, not just because a field is non-null, so I'd love for the test to reflect this.

**Review by jerelmiller — CHANGES_REQUESTED** [review]
Hey @mccraveiro 👋 ! Thanks so much for this fix! 

I think this looks great. I'd be happy to approve and merge if we can wordsmith the description of the test a bit more as I'd like to see if we can capture the scenario that is being tested a bit more. See the comment for more details.

**Review by alessbell — APPROVED** [review]

**Comment by alessbell** [comment]
Went ahead and committed those suggestions, thanks @jerelmiller!

This looks ready to go, thanks @mccraveiro! 🙌

**Comment by mccraveiro** [comment]
Thanks @alessbell and @jerelmiller! I was on vacation and moving to another city so I missed this notification 😉

**Comment by jerelmiller** [comment]
No problem! Hope your vacation was great!
