### PR TITLE
Don't allow `fetchMore` or updates to polling for `cache-only` queries and exclude from `client.refetchQueries`

### LINKED ISSUE #11997: `cache-only` fetchPolicy results in network request after deleting cached data
### Issue Description

When using the `cache-only` fetch policy with `useQuery`, if data is cleared from the cache in a `client.refetchQueries` operation, the query will make a network request, even though that should never happen with a `cache-only` fetch policy.

### Link to Reproduction

https://codesandbox.io/p/sandbox/apollo-cache-policy-issue-dj2w8s

### Reproduction Steps

- Open the reproduction sandbox link above
- Observe that initially only the `NetworkQuery` request is sent, the `cache-only` query does correctly use only the cache
- Click the "refetch" button
- Observe that a `CacheOnlyQuery` network request is made.

### `@apollo/client` version

3.11.4

### PR DESCRIPTION
**Pull request by jerelmiller**
Fixes #11997

Throws an error when `fetchMore` is called on a `cache-only` query. Additionally a warning will be emitted when setting a poll interval on a `cache-only` query and polling will be cancelled.

`cache-only` queries are now excluded from `refetchQueries` when using `include: 'all' | 'active'` and when listed as a query in `include`.

`cache-only` queries are also excluded from `client.reFetchObservableQueries` when `includeStandby` is `true`.

### CODE REVIEW

**Comment by jerelmiller** [comment]
This doesn't quite solve the root issue from https://github.com/apollographql/apollo-client/issues/11997. Using `updateCache` still causes a `refetch` call on the `ObservableQuery` instance but we should try to filter this out unless its explicitly defined with `include`. Will keep at this a bit more.

See https://codesandbox.io/p/devbox/modest-tdd-mswhyd.

File: src/__tests__/refetchQueries.ts [hunk 1]
```diff
@@ -567,6 +716,85 @@ describe("client.refetchQueries", () => {
...
+    await expect(
+      client.refetchQueries({
+        include: [aQuery, cQuery],
+        onQueryUpdated: activeOQU.onQueryUpdated,
+      })
+    ).rejects.toEqual(
+      new InvariantError(
+        "Cannot execute `refetch` for 'cache-only' query 'C'. Please use a different fetch policy."
+      )
+    );
```
Comment (phryneas) [inline src/__tests__/refetchQueries.ts]: What if you have 10 `ObservableQuery` instances with the same query, but different variables and `fetchPolicies` and a single one with `cache-only`?

I think this shouldn't error. It should just be skipped.

File: src/core/ObservableQuery.ts [hunk 2]
```diff
@@ -1217,23 +1248,25 @@ Did you mean to call refetch(variables) instead of refetch({ variables })?`,
...
     } = this;
 
-    if (!pollInterval || !this.hasObservers()) {
+    if (!pollInterval || !this.hasObservers() || fetchPolicy === "cache-only") {
+      if (pollInterval && fetchPolicy === "cache-only") {
+        invariant.warn(
+          "Cannot poll on 'cache-only' query '%s' and as such, polling is disabled. Please use a different fetch policy.",
+          getOperationName(this.query, "(anonymous)")
+        );
+      }
```
Comment (phryneas) [inline src/core/ObservableQuery.ts]: `reobserve`, and as a result `updatePolling` can be called quite often - this shouldn't warn every time. Maybe only once per `ObservableQuery` instance?

File: src/core/QueryManager.ts [hunk 3]
```diff
@@ -1296,6 +1296,13 @@ export class QueryManager {
 
     if (include) {
       this.getObservableQueries(include).forEach((oq) => {
+        if (
+          (include === "active" || include === "all") &&
+          oq.options.fetchPolicy === "cache-only"
+        ) {
+          return;
+        }
+
```
Comment (phryneas) [inline src/core/QueryManager.ts]:
```suggestion
        if (oq.options.fetchPolicy === "cache-only") {
          return;
        }

```

As a result of my previous comment, this should probably do it.

**Review by phryneas — COMMENTED** [review]
One follow-up question might be if we should also disallow it for `standby` queries.

**Comment by jerelmiller** [comment]
I started doing this for `standby` queries but quickly abandoned it because we allow `client.refetchQueries({ include: 'all' })` which specifically fetches `standby` queries. That and `client.reFetchObservableQueries(true)` also fetches standby queries.

I think limiting it to just `cache-only` makes sense given the other functionality, otherwise we'd need to rethink `refetchQueries` with `include: 'all'` vs `active` since that list becomes the same and I'm not sure we care to do that right now.

File: src/__tests__/refetchQueries.ts (hunk 1 above)
Comment (jerelmiller) [reply src/__tests__/refetchQueries.ts]: Fair enough. Should we at least warn if you provide a specific query to `include` that is a `cache-only` query? Or just silently not include it?

File: src/core/ObservableQuery.ts [hunk 4]
```diff
@@ -719,6 +740,16 @@ Did you mean to call refetch(variables) instead of refetch({ variables })?`,
...
     }
   ): Promise<QueryResult<TFetchData>> {
+    if (this.options.fetchPolicy === "cache-only") {
+      const error = newInvariantError(
+        "Cannot execute `fetchMore` for 'cache-only' query '%s'. Please use a different fetch policy.",
+        getOperationName(this.query, "(anonymous)")
+      );
+
+      this.setError(error);
+      return Promise.reject(error);
```
Comment (jerelmiller) [inline src/core/ObservableQuery.ts]: Let's just throw and avoid emitting an error for `fetchMore`.

File: src/core/ObservableQuery.ts [hunk 5]
```diff
@@ -1683,6 +1716,18 @@ Did you mean to call refetch(variables) instead of refetch({ variables })?`,
     });
   }
 
+  private setError(error: ErrorLike) {
```
Comment (jerelmiller) [inline src/core/ObservableQuery.ts]: This can go away

File: src/core/ObservableQuery.ts [hunk 6]
```diff
@@ -660,6 +665,23 @@ export class ObservableQuery<
   public refetch(
     variables?: Partial<TVariables>
   ): ObservableQuery.ResultPromise<QueryResult<TData>> {
+    const { fetchPolicy } = this.options;
+
+    if (fetchPolicy === "cache-only") {
```
Comment (jerelmiller) [inline src/core/ObservableQuery.ts]: Remove this. We will allow `refetch` with cache-only queries.

File: src/core/__tests__/ObservableQuery.ts [hunk 7]
```diff
@@ -1954,6 +2139,44 @@ describe("ObservableQuery", () => {
       expect(observable.options.fetchPolicy).toBe("no-cache");
     });
 
+    it("does not allow refetch on cache-only query", async () => {
```
Comment (jerelmiller) [inline src/core/__tests__/ObservableQuery.ts]: Update to allow this

File: src/core/__tests__/fetchPolicies.ts [hunk 8]
```diff
@@ -599,7 +600,7 @@ describe("cache-first", () => {
 });
 
 describe("cache-only", () => {
-  it("allows explicit refetch to happen", async () => {
+  it("does not allow refetch", async () => {
```
Comment (jerelmiller) [inline src/core/__tests__/fetchPolicies.ts]: Revert back

File: src/react/hooks/__tests__/useLazyQuery.test.tsx [hunk 9]
```diff
@@ -6080,6 +6080,80 @@ test("rerenders with data: undefined when changing variables and an error is ret
   await expect(takeSnapshot).not.toRerender();
 });
 
+test("throws when calling `refetch` on a cache-only query", async () => {
```
Comment (jerelmiller) [inline src/react/hooks/__tests__/useLazyQuery.test.tsx]: Allow this

File: src/react/hooks/__tests__/useQuery.test.tsx [hunk 10]
```diff
@@ -6418,6 +6464,64 @@ describe("useQuery Hook", () => {
       await expect(takeSnapshot).not.toRerender();
     });
 
+    it("does not allow refetch on a cache-only query", async () => {
```
Comment (jerelmiller) [inline src/react/hooks/__tests__/useQuery.test.tsx]: Reverse this

File: .changeset/lemon-pans-sit.md [hunk 11]
```diff
@@ -0,0 +1,5 @@
+---
+"@apollo/client": major
+---
+
+`cache-only` queries are now excluded from `client.refetchQueries` when using `include: 'all'`, `include: 'active'`, or a `cache-only` query is listed in `include`. `cache-only` queries affected by `updateCache` are also excluded from `refetchQueries` when `onQueryUpdated` is not provided.
```
Comment (phryneas) [inline .changeset/lemon-pans-sit.md]:
```suggestion
`cache-only` queries are now excluded from `client.refetchQueries` in all situations. `cache-only` queries affected by `updateCache` are also excluded from `refetchQueries` when `onQueryUpdated` is not provided.
```

File: src/core/ObservableQuery.ts [hunk 12]
```diff
@@ -1207,23 +1216,30 @@ Did you mean to call refetch(variables) instead of refetch({ variables })?`,
...
+        pollInterval &&
+        fetchPolicy === "cache-only"
+      ) {
+        invariant.warn(
+          "Cannot poll on 'cache-only' query '%s' and as such, polling is disabled. Please use a different fetch policy.",
+          getOperationName(this.query, "(anonymous)")
+        );
+        this.didWarnCacheOnlyPolling = true;
+      }
+
```
Comment (phryneas) [inline src/core/ObservableQuery.ts]: The `invariant.warn` would be stripped out in `__DEV__`, but they tests would not be.
```suggestion
      if (__DEV__) {
        if (
          !this.didWarnCacheOnlyPolling &&
          pollInterval &&
          fetchPolicy === "cache-only"
        ) {
          invariant.warn(
            "Cannot poll on 'cache-only' query '%s' and as such, polling is disabled. Please use a different fetch policy.",
            getOperationName(this.query, "(anonymous)")
          );
          this.didWarnCacheOnlyPolling = true;
        }
      }

```

Comment (jerelmiller) [reply src/core/ObservableQuery.ts]: Good call.

**Review by phryneas — APPROVED** [review]
