### PR TITLE
More robust handling of local state default value when read function is defined

### LINKED ISSUE #12930: Incorrect resolution of nested `@client` fields in v4
### Issue Description

I have a query with client field:
```gql
query {
  child {
    clientField @client
    normalField
  }
}
```
And `typePolicies`:
```javascript
typePolicies: {
  Child: {
    fields: {
      clientField: (value = 1) => value,
    },
  },
},
```
When I do `const {data} = await client.query({query})`, I expect `data.child.clientField` to be `1`, **but it's `null` instead**.

I assume it may be helpful:
- With separated `read` and `merge` functions we can see that `merge` is called first in this case, and it writes `null`. *That's the problem.*
- With root fields instead of nested ones, it works properly.
- With `@client` only fields it works properly too.

### Link to Reproduction

https://github.com/broyde/apollo-nested-client-field

### Reproduction Steps

I've created simple jest tests to show the problem.
1. `git clone https://github.com/broyde/apollo-nested-client-field.git`
2. `cd apollo-nested-client-field`
3. `npm i`
4. `npm test`
5. See the test [nested-client-field.test.js](https://github.com/broyde/apollo-nested-client-field/blob/main/nested-client-field.test.js) and how it fails:
```
FAIL ./nested-client-field.test.js
  ● Console

    console.log
      merge { cachedValue: undefined, value: null }

    console.log
      read null

  ● Should resolve nested @client fields properly

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Object {
        "__typename": "Child",
    -   "clientField": 1,
    +   "clientField": null,
        "normalField": 2,
      }

      49 |
      50 |   const {data} = await client.query({query});
    > 51 |   expect(data.child).toEqual({
         |                      ^
      52 |     __typename: 'Child',
      53 |     clientField: 1,
      54 |     normalField: 2,

      at Object.toEqual (nested-client-field.test.js:51:22)
```

### `@apollo/client` version

4.0.5

### PR DESCRIPTION
**Pull request by jerelmiller**
Closes #12930.

Better detect whether the cache can handle resolving a client field and warn if neither a local resolver or read function is defined. If a `read` function is defined, don't set a default value of `null` for the field to allow for the `read` function to set the value. This allows default parameters to work again.

This also adds a check for `no-cache` fetch policies and will warn if used with a `@client` field since the cache is not read. This fixes an issue where using a `no-cache` fetch policy would read from the cache to get the cache `diff` to resolve the field.

### CODE REVIEW

File: src/__tests__/local-state/general.ts [hunk 1]
```diff
@@ -1510,3 +1510,142 @@ test("throws when executing subscriptions with client fields when local state is
...
+        user: {
+          __typename: "User",
+          firstName: null,
+          lastName: "Smith",
+        },
+      },
+    });
+
+    expect(merge).toHaveBeenCalledTimes(1);
+    expect(merge).toHaveBeenCalledWith(undefined, undefined, expect.anything());
```
Comment (jerelmiller) [inline src/__tests__/local-state/general.ts:1649]: This test fails because the `merge` function isn't called at all since it skips them if the incoming value is `undefined`. If the fallback is `null`, it is called where `existing` is `undefined` and `incoming` is `null` which might actually be ok here.

File: src/__tests__/local-state/general.ts [hunk 2]
```diff
@@ -1510,3 +1510,136 @@ test("throws when executing subscriptions with client fields when local state is
...
+      user: {
+        __typename: "User",
+        firstName: "Fallback",
+        lastName: "Smith",
+      },
+    },
+  });
+
+  expect(merge).toHaveBeenCalledTimes(1);
+  expect(merge).toHaveBeenCalledWith(undefined, null, expect.anything());
```
Comment (jerelmiller) [inline src/__tests__/local-state/general.ts:1658]: If a `merge` function is present, we'll call it with `null` as the `incoming` value which I think makes sense since its resolved from `LocalState`. When a `read` function is the only thing defined, the `merge` function won't be called at all because the `incoming` value is set to `undefined` instead and `merge` functions aren't called in this case.

**Comment by jerelmiller** [comment]
@phryneas would love your initial input on this as a potential solution for the issue. I'll open this up and get ready for merge if you like the approach.

File: .changeset/flat-worms-notice.md [hunk 3]
```diff
@@ -0,0 +1,7 @@
+---
+"@apollo/client": minor
```
Comment (jerelmiller) [inline .changeset/flat-worms-notice.md:2]: I marked this as `minor` (in which case we'll want to repoint the branch) since it feels like enough of a change to justify a minor. Happy to update to `patch` though if it feels more like a bug fix. Opinions welcome.

File: .changeset/unlucky-cooks-rhyme.md [hunk 4]
```diff
@@ -0,0 +1,7 @@
+---
+"@apollo/client": minor
```
Comment (jerelmiller) [inline .changeset/unlucky-cooks-rhyme.md:2]: Same. Would like opinions on whether this should be viewed as a minor or patch.

File: src/__tests__/local-state/general.ts [hunk 5]
```diff
@@ -1510,3 +1517,149 @@ test("throws when executing subscriptions with client fields when local state is
...
+
+  expect(console.warn).toHaveBeenCalledTimes(1);
+  expect(console.warn).toHaveBeenCalledWith(
```
Comment (jerelmiller) [inline src/__tests__/local-state/general.ts:1661]: This is one case where the warning feels a bit strange since nothing is really set as "null" unless the `merge` function returns `incoming` (you can see the check on the query result has the value `Fallback`, not `null` for `firstName`).

Should we consider a defined `merge` function as part of the ability to resolve the client field?

File: .changeset/unlucky-cooks-rhyme.md [hunk 6]
```diff
@@ -0,0 +1,7 @@
...
+---
+
+Add an abstract `resolvesClientField` function to `ApolloCache` that can be used by 3rd party caches to determine if it can resolve a `@client` field when a local resolver is not defined.
```
Comment (phryneas) [inline .changeset/unlucky-cooks-rhyme.md]:
```suggestion
Add an abstract `resolvesClientField` function to `ApolloCache` that can be used by caches to announce if it can resolve a `@client` field when a local resolver is not defined.
```

File: .changeset/unlucky-cooks-rhyme.md [hunk 7]
```diff
@@ -0,0 +1,7 @@
...
+
+`LocalState` will emit a warning and set a fallback value of `null` when `resolvesClientField` returns `false`, or isn't defined. Returning `true` from `resolvesClientField` signals that a mechanism in the cache will set the field value. In this case, `LocalState` won't set the field so that `undefined` is used as the initial value.
```
Comment (phryneas) [inline .changeset/unlucky-cooks-rhyme.md]:
```suggestion
`LocalState` will emit a warning and set a fallback value of `null` when no local resolver is defined and `resolvesClientField` returns `false`, or isn't defined. Returning `true` from `resolvesClientField` signals that a mechanism in the cache will set the field value. In this case, `LocalState` won't set the field so that `undefined` is used as the initial value.
```

File: .changeset/shaggy-islands-yell.md [hunk 8]
```diff
@@ -0,0 +1,5 @@
+---
+"@apollo/client": patch
+---
+
+Warn when using a `no-cache` fetch policy when a `@client` field resolves the value from the cache that defines a `read` function.
```
Comment (phryneas) [inline .changeset/shaggy-islands-yell.md]: Can you phrase this differently? Without context, this one might be very difficult to understand.

File: src/local-state/LocalState.ts [hunk 9]
```diff
@@ -703,13 +712,32 @@ export class LocalState<
         // Warn when a resolver is not defined.
       : (
         () => {
+          const { cache } = client;
```
Comment (phryneas) [inline src/local-state/LocalState.ts]: This is only used once - maybe call `client.cache` below?

File: src/local-state/LocalState.ts [hunk 10]
```diff
@@ -703,13 +712,32 @@ export class LocalState<
...
             return fieldFromCache;
           }
 
+          if (cache.resolvesClientField?.(typename, fieldName)) {
+            if (fetchPolicy === "no-cache") {
+              invariant.warn(
+                "The '%s' field resolves the value from the cache, for example from a 'read' function, but a 'no-cache' fetch policy was used. The field value has been set to `null`. Either define a local resolver or use a fetch policy that uses the cache to ensure the field is resolved correctly.",
+                resolverName
+              );
+              return null;
```
Comment (phryneas) [inline src/local-state/LocalState.ts:727]: Do we want to return `null` here even in the `returnPartialData: true` case?

File: src/local-state/LocalState.ts [hunk 11]
```diff
@@ -703,13 +712,32 @@ export class LocalState<
...
+            }
+
+            // assume the cache will handle returning the correct value
+            returnPartialData = true;
```
Comment (phryneas) [inline src/local-state/LocalState.ts:731]: Changing this here will disable the warning and null-returning behaviour a few lines down for all future fields. Do we want that to happen?
Might be necessary to create an immutable copy of the initial `returnPartialData` otherwise.

File: src/__tests__/local-state/general.ts (hunk 5 above)
Comment (jerelmiller) [reply src/__tests__/local-state/general.ts:1661]: Discussed in team meeting and decided this was ok

File: .changeset/shaggy-islands-yell.md (hunk 8 above)
Comment (jerelmiller) [reply .changeset/shaggy-islands-yell.md]: Yeesh this was horrible 😅. Updated in 0ff610d236fa0785899febd01c2d4101eaa38d37

File: .changeset/unlucky-cooks-rhyme.md (hunk 6 above)
Comment (jerelmiller) [reply .changeset/unlucky-cooks-rhyme.md]: 0ff610d236fa0785899febd01c2d4101eaa38d37

File: .changeset/unlucky-cooks-rhyme.md (hunk 7 above)
Comment (jerelmiller) [reply .changeset/unlucky-cooks-rhyme.md]: 0ff610d236fa0785899febd01c2d4101eaa38d37

File: src/local-state/LocalState.ts (hunk 11 above)
Comment (jerelmiller) [reply src/local-state/LocalState.ts:731]: Discussed in person. This is caught by the conditional below that returns early when the value is `null` or `undefined`.

File: src/local-state/LocalState.ts (hunk 10 above)
Comment (jerelmiller) [reply src/local-state/LocalState.ts:727]: I initially thought yet, but I've changed my mind only because there is no other way to resolve the field value. `no-cache` and `returnPartialData` are technically incompatible together since `no-cache` queries don't read from the cache, so there isn't a possibility of a partial result. The same applies here since the value can only be resolved in `LocalState` when a `no-cache` query is issued since the `read` function isn't called. In this case, I think its better to have a `null` to ensure the query is complete since it can't be resolved any other way.

File: src/local-state/LocalState.ts (hunk 9 above)
Comment (jerelmiller) [reply src/local-state/LocalState.ts]: [57c43dd](https://github.com/apollographql/apollo-client/pull/12934/commits/57c43dd3bb28b40a6440dc054f61453599f54a2f)

**Review by phryneas — APPROVED** [review]
Looks good now :)
