### PR TITLE
Fix broken link in error message about fragments

### LINKED ISSUE #5477: Broken link: Fragment Matcher
Broken [link](https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher) in the error message - 
```
You are using the simple (heuristic) fragment matcher, but your queries contain union or interface types. Apollo Client will not be able to accurately map fragments. 
To make this error go away, use the `IntrospectionFragmentMatcher` as described in the docs: https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher
```

### PR DESCRIPTION
**Pull request by dantehemerson**
Fix #5477 

Change with the new link.

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

File: packages/apollo-cache-inmemory/src/fragmentMatcher.ts [hunk 1]
```diff
@@ -94,7 +94,7 @@ export class HeuristicFragmentMatcher implements FragmentMatcherInterface {
           'queries contain union or interface types. Apollo Client will not be ' +
           'able to accurately map fragments. To make this error go away, use ' +
           'the `IntrospectionFragmentMatcher` as described in the docs: ' +
-          'https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher',
+          'https://www.apollographql.com/docs/react/data/fragments/#fragments-on-unions-and-interfaces'
```
Comment (benjamn) [inline packages/apollo-cache-inmemory/src/fragmentMatcher.ts:97]:
```suggestion
          'https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces'
```

**Review by benjamn — APPROVED** [review]
Thanks @dantehemerson!
