### PR TITLE
Stop delivering previous data in unrelated loading results.

### LINKED ISSUE #6039: When variables change, data is the previous result in Query Component
Continuing discussion from the bug apollographql/react-apollo#2202

**Intended outcome:**
I want the `data` returned from `useQuery` to be undefined when the variables change. Reasoning is that if the variables for the query change, `loading` is set to true, but `data` remains set to the data from the previous query with old variables.

**Actual outcome:**
`data` is set to the previous variables `data` while the next query (with new variables) is in flight.

**How to reproduce the issue:**
https://codesandbox.io/s/changing-variables-demo-obykj

**Discussion**
While this may be intended and desired for most cases, I think it would be a good change to add the option for developers to choose if they want this behavior. One example (that caused me to find this issue) was a search bar that searches as you type, but doesn't search for anything (and hides results) if you've only typed less than 3 characters. My issue was that the user could search for something, delete everything, then re-search with different text. When the third character was pressed, `skip` would be set to false, and the search would happen, but there would be a brief moment of showing the data from the old query variables.

I looked at apollographql/react-apollo#2889 by @jcready which had a potential fix for this issue, but looks abandoned. But following the discussion, a few possibilities were discussed as potential fixes to this issue:

1. Adding a `shouldInvalidatePreviousData` option to `useQuery`.
This would allow a developer to write code such as:
```
const { data, loading, error } = useQuery(FIND_DOGS, {
  variables: {
    search: searchText
  },
  shouldInvalidatePreviousData(nextVariables, previousVariables) {
    return nextVariables !== previousVariables;
  }
});
```

2. Adding a `clearPreviousDataOnLoad` option to `useQuery`.
This would allow a developer to write code such as:
```
function usePrevious(value) {
  const ref = useRef();
  useEffect(() => {
    ref.current = value;
  }, [value]);
  return ref.current;
}

...

const previousSearchText = usePrevious(searchText);
const { data, loading, error } = useQuery(FIND_DOGS, {
  variables: {
    search: searchText
  },
  clearPreviousDataOnLoad: searchText !== previousSearchText
});
```

3. A final option that I see as more of a workaround that requires no changes:
https://codesandbox.io/s/cool-brown-ttwxw
```
function usePrevious(value) {
  const ref = useRef();
  useEffect(() => {
    ref.current = value;
  }, [value]);
  return ref.current;
}

...

const previousSearchText = usePrevious(searchText);
const { data, loading, error } = useQuery(FIND_DOGS, {
  variables: {
    search: searchText
  }
});

const showDataWhileLoading = searchText === previousSearchText
const updatedData = !loading || showDataWhileLoading ? data : undefined;
```

I feel the third option is weird to write, and while the first option is probably the easiest from a developer's perspective, the second option would be the easiest to implement

**Versions**

```
System:
  OS: macOS 10.15.3
  Binaries:
    Node: 10.18.1 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.npm-global/bin/yarn
    npm: 6.13.1 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 69.0.2
    Safari: 13.0.5
  npmPackages:
    @apollo/client: ^3.0.0-beta.39 => 3.0.0-beta.39
    @apollo/react-components: 3.2.0-beta.0 => 3.2.0-beta.0
    @apollo/react-hoc: 3.2.0-beta.0 => 3.2.0-beta.0
    apollo-cache-persist: ^0.1.1 => 0.1.1
    apollo-client: ^2.6.4 => 2.6.8
    apollo-link-error: ^1.1.12 => 1.1.12
  npmGlobalPackages:
    apollo: 2.21.3```

### PR DESCRIPTION
**Pull request by benjamn**
Ever since https://github.com/apollographql/react-apollo/pull/1639, Apollo's React functionality has preserved a strange and nonsensical policy of falling back to the _previous_ data for `loading: true` results, even though the previous data may have nothing to do with the current request, as #6039 demonstrates. Results with `loading: true` may provide `data` from the cache (if any), but they should never simply reuse data from a previous result, which may have been derived using different variables. Instead, `result.data` should be undefined for loading states that do not have any partial cache data to provide.

This is potentially a breaking change for code that blindly relied on `result.data` being defined whenever `result.loading` is `true`, but I believe the bugs this change will fix are much more serious than the inconvenience of checking the truthiness of `result.data` before using it. Still, I wish I'd gotten to this sooner.

Fixes #6039, as verified by the [reproduction](https://codesandbox.io/s/changing-variables-demo-obykj) provided by @davismariotti (thanks!).

### CODE REVIEW

File: src/react/data/QueryData.ts [hunk 1]
```diff
@@ -361,22 +361,15 @@ export class QueryData<TData, TVariables> extends OperationData {
...
-        const previousData =
-          this.previousData.result && this.previousData.result.data;
-        result.data =
-          previousData && data
-            ? {
-                ...previousData,
-                ...data
-              }
-            : previousData || data;
+        // Fall through without modifying result...
```
Comment (benjamn) [inline src/react/data/QueryData.ts:372]: We could default `result.data` to an empty object here, if we think that will help reduce the risk of this change.

Comment (hwillson) [reply src/react/data/QueryData.ts:372]: Storing empty objects in `data` has gotten us into trouble in the past (as outlined in https://github.com/apollographql/react-apollo/pull/3388), so I'm all for keeping this as is.

**Comment by jfrolich** [comment]
Might be nonsensical, but it's actually very useful in user interfaces with a filter UI. You'd almost never want to completely go back to a global spinner when a filter is changed. We use this a lot in our app, and it's completely broken after this release. Is this coming back as an option?

**Comment by macrozone** [comment]
@jfrolich absolutly agree! I was blaming all the breakings on the new cache, but a lot of issues was due to this change and its not mentioned as breaking change (or i did not see it)

@jfrolich as a workaround you can do:

```
// store previous data in a ref
 const previousData = useRef<AssortmentFilters["search"]>();
// your query
  const { data, error, loading } = useQuery<
    AssortmentFilters,
    AssortmentFiltersVariables
  >(QUERY, {
    variables: { assortmentId, searchQueryString, filterQuery },
    skip: skip || (!assortmentId && !searchQueryString),
  });

  if (data?.search) {
    previousData.current = data.search;
  }
  const filters = (data?.search ?? previousData.current)?.filters ?? [];

  return { filters, error, loading };
```

**Comment by maapteh** [comment]
For our application this was a big surprise, for the same reason above. Given new arguments to same query now results in total empty data :(

**Comment by robertsmit** [comment]
Is it possible to get the old behavior. For example when typing in a searchField en changing the searchText, it is ok to get the old results for the possible options....

**Comment by kliakos** [comment]
Would be nice to optionally have the old behavior back somehow.

**Comment by eranimo** [comment]
This should have been disabled by default instead of removed entirely. This is a _huge_ breaking change that is not easy to fix.

**Comment by akornato** [comment]
In an async world it is "nonsensical" to think a user never wants to see old data while they wait for new data. I'm sure there's exceptions, but that's what `loading` is for. Fortunately we wrap `useQuery` anyway, thanks @macrozone for the hint how to work around this new behaviour.

**Comment by hwillson** [comment]
Just a heads up, `previousData` is now available alongside `data` in `@apollo/client@next` (see https://github.com/apollographql/apollo-client/pull/7082). 3.3 will be officially published early next week.

**Comment by ctataryn** [comment]
@hwillson FYI I have [added this PR](https://github.com/apollographql/apollo-client/pull/9434) to update the v2 -> v3 migration guide, as this breaking change was a challenge to track down.
