### PR TITLE
Replace existing edges when args.{after,before} not provided.

### LINKED ISSUE #6592: relayStylePagination duplicating results after page refresh
**Intended outcome:**
Expect the same number of results (i.e. 1 list item) on refresh of the page containing the list.

**Actual outcome:**
Each page refresh adds the same 1 list item to the list (causing it to duplicate each time).

**How to reproduce the issue:**
`relayStylePagination` setup like so:
```ts
new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        users: relayStylePagination(['groupId']),
      },
    },
  },
})
```

When `fetchPolicy: 'cache-and-network'` is enabled it refetches the result and when the cache is persisted (i.e. using `apollo-cache-persist`) it remembers the last result. So it's concatenating the same result to the end of the array.

This issue isn't present when using this update function: 
```ts
updateQuery: (previousResult, { fetchMoreResult }) => {
  if (isUndefined(fetchMoreResult)) return previousResult

  const newTotalCount = fetchMoreResult.users.totalCount
  const newEndCursor = fetchMoreResult.users.pageInfo.endCursor
  const newHasNextPage = fetchMoreResult.users.pageInfo.hasNextPage
  const newEdges = fetchMoreResult.users.edges

  return gt(newEdges.length, 0)
    ? {
        ...previousResult,
        users: {
          ...previousResult.users,
          totalCount: newTotalCount,
          pageInfo: {
            ...previousResult.users.pageInfo,
            endCursor: newEndCursor,
            hasNextPage: newHasNextPage,
          },
          edges: [...previousResult.users.edges, ...newEdges],
        },
      }
    : previousResult
},
```

**Versions**
@apollo/client ^3.0.0-rc.10

### PR DESCRIPTION
**Pull request by benjamn**
If the `relayStylePagination` `merge` function receives neither `args.after` nor `args.before`, the incoming edges cannot be spliced into the existing edges by cursor, so they must replace the existing edges.

Should fix #6592.

### CODE REVIEW

File: src/utilities/policies/pagination.ts [hunk 1]
```diff
@@ -99,6 +99,11 @@ export function relayStylePagination<TNode = Reference>(
         const index = prefix.findIndex(edge => edge.cursor === args.before);
         suffix = index < 0 ? prefix : prefix.slice(index);
         prefix = [];
+      } else {
+        // If we have neither args.after nor args.before, the incoming
+        // edges cannot be spliced into the existing edges, so they must
+        // replace the existing edges. See #6592 for a motivating example.
+        prefix = [];
```
Comment (benjamn) [inline src/utilities/policies/pagination.ts:106]: This is the relevant code change (everything else is tests).
