### PR TITLE
Avoid voiding `result.data` in `ObservableQuery#getCurrentResult` when `!diff.complete`

### LINKED ISSUE #7978: Previous data returned when changing variables and fetchPolicy is network-only (Reproduction Provided)
**Intended outcome:**
If I change variable values when `fetchPolicy === 'network-only'`, then `data` should immediately become `undefined` while the results are being fetched from the server. This seemed to work correctly in v3.0.0 - v3.0.2, but broke in v3.1.0.

**Actual outcome:**
When I change the variable values, `data` still holds the previous data which was associated with the previous variable values.

**How to reproduce the issue:**
https://github.com/dylanwulf/react-apollo-error-template (look at the console as you click the radio buttons)

Possibly related to #7058 and #7048

**Versions**
```
System:
    OS: Windows 10 10.0.19042
Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.75)
npmPackages:
    @apollo/client: ^3.3.11 => 3.3.11
```

### PR DESCRIPTION
**Pull request by benjamn**
PR #8422 (released in `@apollo/client@3.4.0-rc.15`) attempted to solve issue #7978 (reported by @dylanwulf) by relying on `queryInfo.getDiff()` to obtain results appropriate for the current `variables`, rather than blindly relying on the `lastResult` stored by the `ObservableQuery` (which may have been obtained using different `variables`).

While this solution appeared to resolve #7978, it introduced a new bug (reported in #8620 by @maxsalven) because the following code now runs unconditionally:
https://github.com/apollographql/apollo-client/blob/bd03ff048ecaf4ddc7aeb2906bf0bdfb2eb695d8/src/core/ObservableQuery.ts#L205-L208
Whenever `!(diff.complete || this.options.returnPartialData)`, this code clobbers `result.data` with `void 0`, even though `result.data` might provide useful information. In the case of #8620, that clobbered information is the missing network result for the A query.

Ideally, we should leave `result.data` unmodified except when `diff.result` is used, as follows:
https://github.com/apollographql/apollo-client/blob/1b1f08576fec9d282034bb950db075be9e3a2a6e/src/core/ObservableQuery.ts#L205-L207

This change helps with issue #8620, but introduces some new test failures, because some of the `result.data` objects that are now delivered (instead of `void 0`) were obtained using different/stale `variables` than the current `this.options.variables`. In other words, these test failures can be prevented if we finish fixing #7978, because the previous result will be appropriately ignored by `getCurrentResult` when the `variables` have changed.

The rest of the commits in this PR fix those tests by tracking a snapshot of the original `variables` associated with the last result, so the `getCurrentResult` method can avoid using `this.last.result` if `this.last.variables` no longer match `this.options.variables`.

I also considered reverting PR #8422 and building back up to a better solution for #7978, but #8422 wasn't all bad, and I was able to make everything work more easily and cleanly with the current approach.

### CODE REVIEW

File: src/core/ObservableQuery.ts [hunk 1]
```diff
@@ -600,15 +614,17 @@ once, rather than every time you call fetchMore.`);
...
-    this.lastResult = newResult;
-    this.lastResultSnapshot = this.queryManager.assumeImmutableResults
-      ? newResult
-      : cloneDeep(newResult);
+    this.last = {
+      ...this.last,
+      result: this.queryManager.assumeImmutableResults
+        ? newResult
+        : cloneDeep(newResult),
+      variables: { ...this.variables } as TVariables,
```
Comment (benjamn) [inline src/core/ObservableQuery.ts:622]: I'm still worried about the delay between passing `options.variables` to `this.fetch` in [`ObservableQuery#reobserve`](https://github.com/apollographql/apollo-client/blob/f14bc92d47fb9974834682d8781e6afdb4669e37/src/core/ObservableQuery.ts#L676) and the delivery of the fetched result to `observer.next`, since the `variables` could have changed during that time, making the `this.last.variables` snapshot inappropriate for `this.last.result`.

File: src/core/ObservableQuery.ts [hunk 2]
```diff
@@ -247,23 +252,33 @@ export class ObservableQuery<
...
+    const last = this.last;
+    if (last &&
+        last[key] &&
+        (!variablesMustMatch || equal(last!.variables, this.variables))) {
+      return last[key];
+    }
   }
 
   // Returns the last result that observer.next was called with. This is not the same as
   // getCurrentResult! If you're not sure which you need, then you probably need getCurrentResult.
```
Comment (hwillson) [inline src/core/ObservableQuery.ts:271]: This comment doesn't quite make sense anymore since `getCurrentResult` is now calling `getLastResult`. I think the naming is clear enough (current vs. last) so we can probably just drop this comment completely.

File: src/core/ObservableQuery.ts [hunk 3]
```diff
@@ -68,9 +74,8 @@ export class ObservableQuery<
   private observers = new Set<Observer<ApolloQueryResult<TData>>>();
   private subscriptions = new Set<ObservableSubscription>();
 
-  private lastResult: ApolloQueryResult<TData> | undefined;
-  private lastResultSnapshot: ApolloQueryResult<TData> | undefined;
-  private lastError: ApolloError | undefined;
+  private last?: Last<TData, TVariables>;
```
Comment (hwillson) [inline src/core/ObservableQuery.ts:77]: So much cleaner! 🎉

**Review by hwillson — APPROVED** [review]
Great fix @benjamn!

File: src/core/ObservableQuery.ts [hunk 4]
```diff
@@ -45,6 +45,12 @@ export interface UpdateQueryOptions<TVariables> {
 
 let warnedAboutUpdateQuery = false;
 
+interface Last<TData, TVars> {
```
Comment (brainkim) [inline src/core/ObservableQuery.ts:48]: It would be nice to consistently use `TVariables` here.

File: src/react/data/QueryData.ts [hunk 5]
```diff
@@ -323,14 +323,13 @@ export class QueryData<TData, TVariables> extends OperationData<
...
     if (currentObservable) {
-      const lastError = currentObservable.getLastError();
-      const lastResult = currentObservable.getLastResult();
-      currentObservable.resetLastResults();
-      this.startQuerySubscription();
-      Object.assign(currentObservable, {
-        lastError,
-        lastResult
-      });
+      const last = currentObservable["last"];
```
Comment (brainkim) [inline src/react/data/QueryData.ts:326]: Can we just make `ObservableQuery.last` public?

File: src/core/ObservableQuery.ts [hunk 6]
```diff
@@ -699,14 +715,14 @@ once, rather than every time you call fetchMore.`);
...
-        ...this.lastResult,
+        ...this.getLastResult(),
         error,
         errors: error.graphQLErrors,
         networkStatus: NetworkStatus.error,
         loading: false,
       } as ApolloQueryResult<TData>);
 
-      iterateObserversSafely(this.observers, 'error', this.lastError = error);
+      iterateObserversSafely(this.observers, 'error', this.last!.error = error);
```
Comment (brainkim) [inline src/core/ObservableQuery.ts:725]: Why are we asserting error as non-null here?

**Review by brainkim — COMMENTED** [review]
My small and smooth brain is unable to understand how methods like `getLastResult()`, `resetLastResult()` and `isDifferentFromLastResult()` are supposed to be used. How would we communicate their purpose to users who directly call `client.watchQuery()`?

Nevertheless, if this fixes issues for users, I guess it should be merged.

File: src/core/ObservableQuery.ts (hunk 3 above)
Comment (brainkim) [reply src/core/ObservableQuery.ts:77]: As long as we don’t move the type to a separate file I don’t mind I guess 😸

File: src/react/data/QueryData.ts (hunk 5 above)
Comment (benjamn) [reply src/react/data/QueryData.ts:326]: Please no! The way I see it, since `ObservableQuery` is a public API, I was able to do this refactoring with confidence only because the `lastResult`, `lastResultSnapshot`, and `lastError` properties were previously `private`, so I'd very much like to preserve that refactoring freedom.

For what it's worth, this `currentObservable["last"]` syntax will be more type-safe than the previous usage of `Object.assign`, which was especially difficult to track down because TS had no complaints about it. I like to use this syntax for stuff that's private within the scope of the `@apollo/client` package and its nested sub-packages.

File: src/core/ObservableQuery.ts (hunk 6 above)
Comment (benjamn) [reply src/core/ObservableQuery.ts:725]: Because calling `this.updateLastResult(...)` immediately above guarantees `this.last` is always defined here.

**Comment by brainkim** [comment]
LGTM so I can rebase against this in #8596

File: src/core/ObservableQuery.ts (hunk 2 above)
Comment (benjamn) [reply src/core/ObservableQuery.ts]: e1a1ceb4eb4bf1a96f1b3a1552fa14cd7809be33

File: src/core/ObservableQuery.ts (hunk 4 above)
Comment (benjamn) [reply src/core/ObservableQuery.ts]: Done as part of c8340894205bd7fd466262a6c648a8f0ddd164bd

File: src/core/ObservableQuery.ts (hunk 1 above)
Comment (benjamn) [reply src/core/ObservableQuery.ts]: addressed by c8340894205bd7fd466262a6c648a8f0ddd164bd
