### PR TITLE
[4.0] fix commonJS build

### LINKED ISSUE #12452: [4.0] Cannot read properties of undefined (reading 'cache.fragmentQueryDocuments')
### Issue Description

Good evening apollo team!

Wanted to get this one on your radar-- with testing the 4.0 alpha, I am seeing a 
`Cannot read properties of undefined (reading 'cache.fragmentQueryDocuments')`

error in: `cache/core/cache.ts:361:24`

This seems to be due to the fact that `defaultCacheSizes` is not exported with the new cjs compilation method in the alpha. And what the non-cjs route does during transpilation is set the value to 1000 directly instead of using the object. 

I believe it was this one that brought this in: https://github.com/apollographql/apollo-client/commit/61febe4ef8712a2035d7ac89ea7283138db5229d 

Some files to look at (in the packaged package!):
- `./cache/core/cache.js:140` --> it's 1000 instead of using the defaultCacheSizes.
- `./__cjs/cache/core/cache.cjs:147` --> it's actually using the `utilities_1.defaultCacheSizes` object.

 
I would also like to move over to ESM, which might fix this, but in a corporate setting that's a bit harder than expected :(

### Link to Reproduction

https://github.com/tthornton3-chwy/react-apollo-error-template

### Reproduction Steps

`npm run test`

should be all you need! Let me know if you need any more info/context!

### `@apollo/client` version

4.0.0-alpha.1

### PR DESCRIPTION
**Pull request by phryneas**
Fixes #12452 

See build output comparison:

https://github.com/apollographql/apollo-client/actions/runs/13928806995?pr=12454

### CODE REVIEW

File: config/compileTs.ts [hunk 1]
```diff
@@ -8,8 +11,23 @@ export const compileTs: BuildStep = async (options) => {
...
+    try {
+      // module `node18` will compile to CommonJS if the [detected module format](https://www.typescriptlang.org/docs/handbook/modules/reference.html#module-format-detection)
+      // is CommonJS, so we temporarily overwrite the `package.json` file
+      // this is the right way to build CommonJS, the `commonjs` module option should actually not be used
+      // see https://www.typescriptlang.org/docs/handbook/modules/reference.html#commonjs
+      const packageJson = JSON.parse(originalPackageJson);
+      packageJson.type = "commonjs";
+      writeFile(packageJsonPath, JSON.stringify(packageJson, null, 2));
+      // noCheck is required to suppress errors like
+      // error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
```
Comment (phryneas) [inline config/compileTs.ts:25]: This might still be a problem and it's annoying that I can't just oppress this kind of error, but at least we're one step ahead.
This *probably* doesn't actually matter since in reality, all those packages should (?) actually resolve fine in node16?

Alas, here's the full output, and we should probable revisit the `package.json` in all of those packages in the long term:

```
src/cache/core/cache.ts:1:27 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/caches")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { WeakCache } from "@wry/caches";
                            ~~~~~~~~~~~~~

src/cache/core/cache.ts:7:22 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("optimism")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

7 import { wrap } from "optimism";
                       ~~~~~~~~~~

src/cache/inmemory/entityStore.ts:1:23 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { equal } from "@wry/equality";
                        ~~~~~~~~~~~~~~~

src/cache/inmemory/entityStore.ts:2:22 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/trie")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

2 import { Trie } from "@wry/trie";
                       ~~~~~~~~~~~

src/cache/inmemory/entityStore.ts:4:51 - error TS1541: Type-only import of an ECMAScript module from a CommonJS module must have a 'resolution-mode' attribute.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

4 import type { OptimisticDependencyFunction } from "optimism";
                                                    ~~~~~~~~~~

src/cache/inmemory/entityStore.ts:5:21 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("optimism")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

5 import { dep } from "optimism";
                      ~~~~~~~~~~

src/cache/inmemory/fragmentRegistry.ts:1:27 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/caches")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { WeakCache } from "@wry/caches";
                            ~~~~~~~~~~~~~

src/cache/inmemory/fragmentRegistry.ts:9:22 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("optimism")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

9 import { wrap } from "optimism";
                       ~~~~~~~~~~

src/cache/inmemory/inMemoryCache.ts:1:23 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { equal } from "@wry/equality";
                        ~~~~~~~~~~~~~~~

src/cache/inmemory/inMemoryCache.ts:7:48 - error TS1541: Type-only import of an ECMAScript module from a CommonJS module must have a 'resolution-mode' attribute.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

7 import type { OptimisticWrapperFunction } from "optimism";
                                                 ~~~~~~~~~~

src/cache/inmemory/inMemoryCache.ts:8:22 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("optimism")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

8 import { wrap } from "optimism";
                       ~~~~~~~~~~

src/cache/inmemory/object-canon.ts:1:22 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/trie")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { Trie } from "@wry/trie";
                       ~~~~~~~~~~~

src/cache/inmemory/reactiveVars.ts:1:51 - error TS1541: Type-only import of an ECMAScript module from a CommonJS module must have a 'resolution-mode' attribute.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import type { OptimisticDependencyFunction } from "optimism";
                                                    ~~~~~~~~~~

src/cache/inmemory/reactiveVars.ts:2:27 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("optimism")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

2 import { dep, Slot } from "optimism";
                            ~~~~~~~~~~

src/cache/inmemory/readFromStore.ts:3:48 - error TS1541: Type-only import of an ECMAScript module from a CommonJS module must have a 'resolution-mode' attribute.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

3 import type { OptimisticWrapperFunction } from "optimism";
                                                 ~~~~~~~~~~

src/cache/inmemory/readFromStore.ts:4:22 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("optimism")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

4 import { wrap } from "optimism";
                       ~~~~~~~~~~

src/cache/inmemory/writeToStore.ts:1:23 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { equal } from "@wry/equality";
                        ~~~~~~~~~~~~~~~

src/cache/inmemory/writeToStore.ts:2:22 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/trie")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

2 import { Trie } from "@wry/trie";
                       ~~~~~~~~~~~

src/config/jest/resolver.ts:19:26 - error TS1470: The 'import.meta' meta-property is not allowed in files which will build into CommonJS output.

19     return fileURLToPath(import.meta.resolve(path));
                            ~~~~~~~~~~~

src/core/equalByQuery.ts:1:19 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import equal from "@wry/equality";
                    ~~~~~~~~~~~~~~~

src/core/ObservableQuery.ts:1:23 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { equal } from "@wry/equality";
                        ~~~~~~~~~~~~~~~

src/core/QueryInfo.ts:1:23 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { equal } from "@wry/equality";
                        ~~~~~~~~~~~~~~~

src/core/QueryManager.ts:1:22 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/trie")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { Trie } from "@wry/trie";
                       ~~~~~~~~~~~

src/link/remove-typename/removeTypenameFromVariables.ts:1:27 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/caches")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { WeakCache } from "@wry/caches";
                            ~~~~~~~~~~~~~

src/link/remove-typename/removeTypenameFromVariables.ts:4:22 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("optimism")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

4 import { wrap } from "optimism";
                       ~~~~~~~~~~

src/masking/__benches__/types.bench.ts:1:31 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@ark/attest")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { attest, bench } from "@ark/attest";
                                ~~~~~~~~~~~~~

src/masking/__benches__/types.bench.ts:2:23 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@ark/attest")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

2 import { setup } from "@ark/attest";
                        ~~~~~~~~~~~~~

src/masking/maskFragment.ts:1:19 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import equal from "@wry/equality";
                    ~~~~~~~~~~~~~~~

src/masking/utils.ts:1:22 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("optimism")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { Slot } from "optimism";
                       ~~~~~~~~~~

src/react/hooks/internal/useDeepMemo.ts:1:23 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { equal } from "@wry/equality";
                        ~~~~~~~~~~~~~~~

src/react/hooks/useFragment.ts:1:19 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import equal from "@wry/equality";
                    ~~~~~~~~~~~~~~~

src/react/hooks/useLazyQuery.ts:2:23 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

2 import { equal } from "@wry/equality";
                        ~~~~~~~~~~~~~~~

src/react/hooks/useMutation.ts:2:23 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

2 import { equal } from "@wry/equality";
                        ~~~~~~~~~~~~~~~

src/react/hooks/useQuery.ts:18:23 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

18 import { equal } from "@wry/equality";
                         ~~~~~~~~~~~~~~~

src/react/hooks/useSubscription.ts:2:23 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

2 import { equal } from "@wry/equality";
                        ~~~~~~~~~~~~~~~

src/react/internal/cache/FragmentReference.ts:1:23 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { equal } from "@wry/equality";
                        ~~~~~~~~~~~~~~~

src/react/internal/cache/QueryReference.ts:1:23 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { equal } from "@wry/equality";
                        ~~~~~~~~~~~~~~~

src/react/internal/cache/SuspenseCache.ts:1:22 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/trie")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { Trie } from "@wry/trie";
                       ~~~~~~~~~~~

src/react/ssr/RenderPromises.ts:1:22 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/trie")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { Trie } from "@wry/trie";
                       ~~~~~~~~~~~

src/testing/core/mocking/mockLink.ts:1:23 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/equality")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { equal } from "@wry/equality";
                        ~~~~~~~~~~~~~~~

src/utilities/caching/caches.ts:1:40 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/caches")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { StrongCache, WeakCache } from "@wry/caches";
                                         ~~~~~~~~~~~~~

src/utilities/graphql/DocumentTransform.ts:1:27 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/caches")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import { WeakCache } from "@wry/caches";
                            ~~~~~~~~~~~~~

src/utilities/graphql/DocumentTransform.ts:2:22 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@wry/trie")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

2 import { Trie } from "@wry/trie";
                       ~~~~~~~~~~~

src/utilities/graphql/DocumentTransform.ts:4:22 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("optimism")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

4 import { wrap } from "optimism";
                       ~~~~~~~~~~

src/utilities/internal/getMemoryInternals.ts:1:48 - error TS1541: Type-only import of an ECMAScript module from a CommonJS module must have a 'resolution-mode' attribute.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import type { OptimisticWrapperFunction } from "optimism";
                                                 ~~~~~~~~~~
```

File: config/compileTs.ts [hunk 2]
```diff
@@ -8,8 +11,23 @@ export const compileTs: BuildStep = async (options) => {
   if (options.type === "esm") {
     await $`npx tsc --project tsconfig.build.json --outDir ${options.targetDir}`;
   } else {
-    // for a `commonjs` output, we have to specify `moduleResulution: node`, and as that will error because it cannot verify some imports, we add `--noCheck`
-    await $`npx tsc --project tsconfig.build.json --outDir ${options.targetDir} --module commonjs --moduleResolution node --noCheck`;
+    const packageJsonPath = join(import.meta.dirname, "..", `package.json`);
+    const originalPackageJson = await readFile(packageJsonPath, "utf-8");
+    try {
+      // module `node18` will compile to CommonJS if the [detected module format](https://www.typescriptlang.org/docs/handbook/modules/reference.html#module-format-detection)
```
Comment (phryneas) [inline config/compileTs.ts:17]: Here it's `node16`, but I'd like to bump this to `node18` once we update TypeScript to the most recent version.

**Review by jerelmiller — APPROVED** [review]
Wild how different the output is on the return type end of things. Glad to see the values replaced properly though. Thanks for fixing this!
