### PR TITLE
Guard against missing this.data[dataId] object in EntityStore#get.

### LINKED ISSUE #5793: [3.0] EntityStore error after calling cache.evict
**Scenario**
Executing the following line of code:
```
  apolloClient.cache.evict(defaultDataIdFromObject(user));
```

**Intended outcome:**
Evict succeeds, with no subsequent error

**Actual outcome:**
An error is thrown with the following message: _TypeError: Cannot convert undefined or null to object_

The following further info is shown in the error details:
```
TypeError: Cannot convert undefined or null to object
Layer.EntityStore.get
entityStore.js:28
  25 |     var storeObject = this.data[dataId];
  26 |     if (!fieldName)
  27 |         return storeObject;
  28 |     if (hasOwn.call(storeObject, fieldName)) {
  29 |         return storeObject[fieldName];
  30 |     }
  31 | }
```

**How to reproduce the issue:**
This error started just by adding cache.evict. I am not entirely sure of the prerequisite conditions. I will spend time reproducing in the apollo error template if the cause of this issue is not obvious to the apollo team

**Versions**
System:
    OS: macOS 10.15.2
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Safari: 13.0.4
  npmPackages:
    @apollo/client: v3.0.0-beta.23  => 3.0.0-beta.23 
    @apollo/react-hooks: ^3.2.0-beta.0 => 3.2.0-beta.0 
    apollo-link-debounce: ^2.1.0 => 2.1.0

### PR DESCRIPTION
**Pull request by benjamn**
Should fix #5793, which was due to a bug I introduced in #5772.

### CODE REVIEW

**Comment by benjamn** [comment]
@hwillson I didn't mean to push 451a22f89e694c4c6bb059a716fd76b10daa9bb1 in this PR, but I think it might be easier to review here than in a separate PR, if you don't mind…?

File: src/cache/inmemory/entityStore.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ export abstract class EntityStore implements NormalizedCache {
     if (hasOwn.call(this.data, dataId)) {
       const storeObject = this.data[dataId];
       if (!fieldName) return storeObject;
-      if (hasOwn.call(storeObject, fieldName)) {
+      if (storeObject && hasOwn.call(storeObject, fieldName)) {
```
Comment (benjamn) [inline src/cache/inmemory/entityStore.ts]: This is the operative change that fixes #5793.

File: src/cache/inmemory/__tests__/entityStore.ts [hunk 2]
```diff
@@ -1219,4 +1219,139 @@ describe('EntityStore', () => {
...
+      },
+      ROOT_QUERY: {
+        __typename: "Query",
+        book: { __ref: "Book:1" },
+      },
+    });
+
+    expect(cache.evict(authorId)).toBe(false);
+
+    expect(cache.diff({
```
Comment (benjamn) [inline src/cache/inmemory/__tests__/entityStore.ts]: This `cache.diff` fails without the `storeObject` check, due to the dangling reference `{ __ref: "Author:2" }` after the `cache.evict` call. This was the best way to reproduce #5793 that I could come up with.
