### PR TITLE
Clear setTimeout handle in stopPollingQuery()

### LINKED ISSUE #4948: toggling polling several times sends extra requests
**Intended outcome:**
stop polling stops polling even after several stop/startPolling calls

**Actual outcome:**
Previous startPolling requests are still resolved if calls to start/stopPolling happen more often then polling interval

**How to reproduce the issue:**

If you call .startPolling -> .stopPolling -> startPolling within polling interval, requests from both first startPolling call and second startPolling call will be sent. This happens because interval is not cleared when query manager [removes pollingInfo](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts#L1405) and new pollRequest sets ```this.pollingInfoByQueryId``` value again and then [maybeFetch](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/core/QueryManager.ts#L1373) finds info from new startPolling call and makes a call.
I wrote a test to demonstrate the issue:
```
it('should cancel polling request on stopPolling', () => {
      const query = gql`
        query fetchLeia($id: String) {
          people_one(id: $id) {
            name
          }
        }
      `;

      const variables = {
        id: '2',
      };

      const data1 = {
        people_one: {
          name: 'Leia Skywalker',
        },
      };

      const queryManager = mockQueryManager(
        {
          request: { query, variables },
          result: { data: data1 },
        },
      );
      const observable = queryManager.watchQuery({
        query,
        variables,
        pollInterval: 50,
      });

      return observableToPromise(
       // use value between timeout(20) + polling interval(50) and polling interval
       // nothing should happen during this time
       //
        { observable, wait: 60 },
        result => {
          expect(stripSymbols(result.data)).toEqual(data1);
          observable.stopPolling();
          observable.startPolling(50);
          setTimeout(() => {
            observable.stopPolling();
            observable.startPolling(50);
            // interval is less then polling interval
          }, 20);
        },
      );
    });
```
**Versions**

System:
    OS: macOS 10.14.4
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 5.10.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.80
    Safari: 12.1
  npmPackages:
    apollo-boost: file:packages/apollo-boost => 0.4.2 
    apollo-cache: file:packages/apollo-cache => 1.3.2 
    apollo-cache-inmemory: file:packages/apollo-cache-inmemory => 1.6.2 
    apollo-client: file:packages/apollo-client => 2.6.2 
    apollo-utilities: file:packages/apollo-utilities => 1.3.2 

**P.S.** 
I can send a pull request to fix this issue, seems pretty quick fix

### PR DESCRIPTION
**Pull request by normanzb**
This PR fixes #4948 and #5444, when `startPolling()` is called immediately after `stopPolling()`, it tricks `maybeFetch()` into believing the scheduled task is still valid (as it takes pollingInfo's existence before go ahead to call `fetchQuery()`).

This leads to extra query be fetched.

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

File: packages/apollo-client/src/core/QueryManager.ts [hunk 1]
```diff
@@ -1403,6 +1403,10 @@ export class QueryManager<TStore> {
   }
 
   public stopPollingQuery(queryId: string) {
+    const info = this.pollingInfoByQueryId.get(queryId)
+    if (info){
+      clearTimeout(info.timeout)
```
Comment (benjamn) [inline packages/apollo-client/src/core/QueryManager.ts:1408]:
```suggestion
    const info = this.pollingInfoByQueryId.get(queryId);
    if (info) {
      clearTimeout(info.timeout);
```
Just some nits that I'll merge myself.
