### PR TITLE
Fix navigator undefined on React Native

### LINKED ISSUE #3137: Navigator on React Native is undefined
```
          if (navigator && navigator.userAgent.indexOf('Chrome') > -1) {
            // tslint:disable-next-line
            console.debug(
              'Download the Apollo DevTools ' +
                'for a better development experience: ' +
                'https://chrome.google.com/webstore/detail/apollo-client-developer-t/jdkknkkbebbapilgoeccciglkfbmbnfm',
            );
          }
```

### PR DESCRIPTION
**Pull request by radko93**
Small PR as everything is in the issue - fixes #3137 

### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests
- [x] If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.

### CODE REVIEW

**Comment by radko93** [comment]
@peggyrayzis done, thanks!

File: packages/apollo-client/src/ApolloClient.ts [hunk 1]
```diff
@@ -167,7 +167,7 @@ export default class ApolloClient<TCacheShape> implements DataProxy {
           typeof (window as any).__APOLLO_DEVTOOLS_GLOBAL_HOOK__ === 'undefined'
         ) {
           // Only for Chrome
-          if (navigator.userAgent.indexOf('Chrome') > -1) {
+          if (window.navigator && window.navigator.userAgent.indexOf('Chrome') > -1) {
```
Comment (gastonmorixe) [inline packages/apollo-client/src/ApolloClient.ts]: This is not solved. I still receive error in RN.

It should be 

```
if (window && 
window.navigator && 
window.navigator.userAgent && 
window.navigator.userAgent.indexOf('Chrome') > -1)```
