### PR TITLE
Fix a potential memory leak where Trie nodes would remain in memory too long.

### LINKED ISSUE #13074: Memory leak in SSR: defaultKeyTrie singleton in optimism accumulates indefinitely
## Intended Outcome

We expected that following Apollo's SSR best practices would result in stable memory usage on our long-running SSR server:

- Creating a **new `ApolloClient` instance per request**
- Configuring **`apollo.cacheSize` limits** before Apollo imports
- Calling **`cache.gc()`, `client.clearStore()`, and `client.stop()`** after each request
- Setting **`resultCaching: false`** in InMemoryCache config

With these mitigations, memory used by each request should be fully garbage collected after the request completes.

## Actual Outcome

**Memory leaks continuously on the SSR server**, growing from 35 MB to 91 MB (+160%) over ~1.5 hours of production traffic.

### Heap Snapshot Evidence

Using `memlab analyze unbound-shape` to compare heap snapshots:

```
┌─────────────────────────┬────────────┬────────────┬────────┐
│ Shape                   │ Snapshot 1 │ Snapshot 2 │ Growth │
├─────────────────────────┼────────────┼────────────┼────────┤
│ Entry (optimism)        │ 148 KB     │ 27 MB      │ x182   │
│ Trie nodes              │ 9.3 KB     │ 1.9 MB     │ x204   │
│ { definitions, kind }   │ 657 KB     │ 21.1 MB    │ x32    │
│ WeakCache               │ 13.5 KB    │ 1.9 MB     │ x141   │
└─────────────────────────┴────────────┴────────────┴────────┘
```

### Root Cause

The `defaultKeyTrie` singleton in `optimism/lib/bundle.cjs` is **shared across ALL ApolloClient instances**:

```javascript
// MODULE-LEVEL singleton - shared across ALL requests!
var defaultKeyTrie;

function defaultMakeCacheKey() {
  var trie = defaultKeyTrie || (defaultKeyTrie = new Trie(true));
  return trie.lookupArray(args);
}
```

**Why this causes memory accumulation:**

1. GraphQL documents are statically imported → they live **forever** in Node.js process
2. `defaultKeyTrie` uses WeakMaps internally with documents as keys
3. WeakMap entries persist **as long as the key is alive**
4. Since documents never die, Trie nodes and Entry objects **accumulate indefinitely**
5. Creating a NEW `ApolloClient` per request doesn't help - they all use the **SAME `defaultKeyTrie`**!

### Why Documented Mitigations Don't Work

| Mitigation                   | Why It Doesn't Help                                             |
|------------------------------|-----------------------------------------------------------------|
| New ApolloClient per request | All clients share `defaultKeyTrie` singleton                    |
| `apollo.cacheSize` config    | Only affects `AutoCleanedWeakCache`, not `defaultKeyTrie`       |
| `cache.gc()`                 | Cleans InMemoryCache, not optimism's Trie                       |
| `client.clearStore()`        | Clears cache data, not memoization keys                         |
| `resultCaching: false`       | Disables result cache, but `wrap()` still uses `defaultKeyTrie` |

### Minimal Reproduction

1. Create an Express SSR server using Apollo Client with `ssrMode: true`
2. Create a new `ApolloClient` per request (following docs)
3. Run `prerenderStatic()` or `getDataFromTree()` for each request
4. Clean up with `cache.gc()`, `clearStore()`, `stop()`
5. Send continuous traffic to the server
6. Take heap snapshots at intervals using `v8.writeHeapSnapshot()`
7. Analyze with `memlab analyze unbound-shape` or Chrome DevTools

### Expected vs Actual

- **Expected**: Memory stays stable as each request is cleaned up
- **Actual**: `Entry` and `Trie` objects grow unbounded

### Our Environment

- **@apollo/client**: 4.0.9
- **optimism**: 0.18.1
- **@wry/trie**: 0.5.0
- **Node.js**: 20.x
- **Framework**: Custom Express SSR server (not Next.js)

### Architecture Context

```
┌─────────────────────────────────────────────────────────────────────────────┐
│                              BROWSER                                         │
│  ┌─────────────────────────────────────────────────────────────────────┐    │
│  │                     React SPA + Apollo Client                        │    │
│  │  - Single ApolloClient instance (persists across navigation)         │    │
│  │  - InMemoryCache with hydration from window.__APOLLO_STATE__         │    │
│  │  - Normal memoization behavior (beneficial for UX)                   │    │
│  └─────────────────────────────────────────────────────────────────────┘    │
└─────────────────────────────────────────────────────────────────────────────┘
                                      │
                                      │ HTTP requests
                                      ▼
┌─────────────────────────────────────────────────────────────────────────────┐
│                           SSR SERVER (Node.js)                               │
│  ┌─────────────────────────────────────────────────────────────────────┐    │
│  │                    Express + Apollo SSR                              │    │
│  │                                                                      │    │
│  │  For EACH request:                                                   │    │
│  │    1. Create NEW ApolloClient instance                               │    │
│  │    2. Create NEW InMemoryCache with SSR-specific config              │    │
│  │    3. Run prerenderStatic() / getDataFromTree()                      │    │
│  │    4. Extract cache state, render HTML                               │    │
│  │    5. Cleanup: cache.gc(), client.clearStore(), client.stop()        │    │
│  │                                                                      │    │
│  │  SSR Cache Config (reduced limits):                                  │    │
│  │    - resultCaching: false                                            │    │
│  │    - fragments: undefined                                            │    │
│  │    - apollo.cacheSize limits configured                              │    │
│  └─────────────────────────────────────────────────────────────────────┘    │
└─────────────────────────────────────────────────────────────────────────────┘
```

### SSR Handler Code

```typescript
// SSR-specific cache config (reduced limits for server)
const getSSRCacheConfig = () => ({
  ...getCacheConfig(),
  fragments: undefined,
  resultCaching: false,
});

// Global cache size limits (set BEFORE Apollo imports)
(globalThis as any)[Symbol.for('apollo.cacheSize')] = {
  checkDocument: 100,
  print: 100,
  parser: 100,
  'documentTransform.cache': 50,
  'queryManager.getDocumentInfo': 100,
  'PersistedQueryLink.persistedQueryHashes': 50,
};

// Per-request ApolloClient (as recommended in #11242)
export default async function ssrHandler(req, res) {
  const apolloClient = new ApolloClient({
    ssrMode: true,
    cache: new InMemoryCache(getSSRCacheConfig()),
    link: createHttpLink({ uri: GRAPHQL_URI }),
  });

  try {
    const { result } = await prerenderStatic({ tree: <App />, ... });
    res.send(renderToHtml(result));
  } finally {
    // Cleanup as recommended
    apolloClient.cache.gc();
    apolloClient.clearStore();
    apolloClient.stop();
  }
}
```

## Our Workaround: Per-Request Trie via AsyncLocalStorage

We patched `optimism` to allow SSR-isolated Tries using Node.js `AsyncLocalStorage`:

### Patch for optimism

```diff
 var defaultKeyTrie;
+var ssrTrieGetter = null;
+
+function setSSRTrieGetter(getter) {
+    ssrTrieGetter = getter;
+}
+
 function defaultMakeCacheKey() {
     var args = [];
     for (var _i = 0; _i < arguments.length; _i++) {
         args[_i] = arguments[_i];
     }
+    // Check for SSR-isolated Trie first
+    if (ssrTrieGetter) {
+        var ssrTrie = ssrTrieGetter();
+        if (ssrTrie) {
+            return ssrTrie.lookupArray(args);
+        }
+    }
+    // Fallback to global defaultKeyTrie (browser or non-SSR context)
     var trie = defaultKeyTrie || (defaultKeyTrie = new Trie(true));
     return trie.lookupArray(args);
 }
+
+exports.setSSRTrieGetter = setSSRTrieGetter;
```

### SSR Trie Context

```typescript
import { AsyncLocalStorage } from 'async_hooks';
import { Trie } from '@wry/trie';
import { setSSRTrieGetter } from 'optimism';

const ssrTrieStorage = new AsyncLocalStorage<Trie<object>>();

// Register getter at module load (before any Apollo imports)
setSSRTrieGetter(() => ssrTrieStorage.getStore() ?? null);

export function runWithSSRTrie<T>(fn: () => Promise<T>): Promise<T> {
  const requestTrie = new Trie<object>(true);
  return ssrTrieStorage.run(requestTrie, fn);
}
```

### Updated SSR Handler

```typescript
import { runWithSSRTrie } from './ssrTrieContext';

export default async function ssrHandler(req, res) {
  // Each request gets its own isolated Trie
  return runWithSSRTrie(async () => {
    const apolloClient = new ApolloClient({ ssrMode: true, ... });
    try {
      const { result } = await prerenderStatic({ tree: <App />, ... });
      res.send(renderToHtml(result));
    } finally {
      apolloClient.cache.gc();
      apolloClient.clearStore();
      apolloClient.stop();
    }
  }); // requestTrie goes out of scope → GC'd with all its Entry objects
}
```

### Why This Works

```
Request 1:
  runWithSSRTrie() creates requestTrie1
  └── All wrap() calls use requestTrie1
  └── Request ends → requestTrie1 out of scope → GC'd ✓

Request 2:
  runWithSSRTrie() creates requestTrie2
  └── All wrap() calls use requestTrie2
  └── Request ends → requestTrie2 out of scope → GC'd ✓

Browser (unaffected):
  ssrTrieGetter returns null
  └── Uses defaultKeyTrie as before
  └── Normal memoization behavior preserved ✓
```

## Suggested Official Fix

Consider one of these approaches:

### Option 1: SSR-aware `defaultMakeCacheKey`

Add an official API similar to our patch - allow consumers to provide a custom Trie getter for SSR isolation.

### Option 2: Request-scoped Trie in Apollo Client

When `ssrMode: true`, Apollo Client could automatically create a per-instance Trie instead of using the global singleton.

### Option 3: Document the limitation

At minimum, document that `defaultKeyTrie` is a global singleton and explain why creating new `ApolloClient` per request doesn't fully prevent memory accumulation in long-running SSR servers.

### PR DESCRIPTION
**Pull request by phryneas**
Fixes #13074

### CODE REVIEW

File: src/cache/core/cache.ts [hunk 1]
```diff
@@ -427,6 +428,7 @@ export abstract class ApolloCache {
       cacheSizes["cache.fragmentQueryDocuments"] ||
```
Comment (phryneas) [inline src/cache/core/cache.ts:428]: You can ignore above error - it happens when the compare build output step tries to build the old sources with the new patch to the types of `optimism`.

File: src/utilities/internal/bindCacheKey.ts
Comment (jerelmiller) [inline src/utilities/internal/bindCacheKey.ts:1]: [nit] Can you name this file `bindCacheKey` to match the function name?

**Review by jerelmiller — APPROVED** [review]
Looks great to me!
