### PR TITLE
Enable strict mode in tsconfig and fix type errors

### LINKED ISSUE #11199: Enable `strict` setting in tsconfig.json
### Issue Description

Our codebase does not currently use the `strict` setting for our codebase. Enabling this causes our codebase to fail due to the [`strictFunctionTypes` rule](https://www.typescriptlang.org/tsconfig#strictFunctionTypes).

As a best practice, we should be using `strict` to avoid subtle bugs that may arise without this enabled.

### Link to Reproduction

The codebase

### Reproduction Steps

Add `strict: true` to `tsconfig.json` and watch all the tests fail due to TS issues (primarily with `src/utilities/graphql/transform.ts`).

### PR DESCRIPTION
**Pull request by jerelmiller**
Closes #11199

Enables strict mode in our `tsconfig.json` and ensures our types/code are updated to handle the failures that arise from this change.

### Checklist:

- [x] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

File: src/utilities/common/filterInPlace.ts [hunk 1]
```diff
@@ -1,14 +0,0 @@
-export function filterInPlace<T>(
```
Comment (jerelmiller) [inline src/utilities/common/filterInPlace.ts:1]: This file isn't used anywhere, nor is it exported. Hooray for removing unused code 🎉

File: src/link/http/HttpLink.ts [hunk 2]
```diff
@@ -1,10 +1,8 @@
-import type { RequestHandler } from "../core/index.js";
 import { ApolloLink } from "../core/index.js";
 import type { HttpOptions } from "./selectHttpOptionsAndBody.js";
 import { createHttpLink } from "./createHttpLink.js";
 
 export class HttpLink extends ApolloLink {
-  public requester: RequestHandler;
   constructor(public options: HttpOptions = {}) {
```
Comment (phryneas) [inline src/link/http/HttpLink.ts:6]: `requester` appears in the whole code base only here and it doesn't seem to be set or read anywhere - it's also not there at runtime. I guess this can be removed?

File: src/react/hoc/mutation-hoc.tsx [hunk 3]
```diff
@@ -86,6 +86,7 @@ export function withMutation<
 
         return (
           <Mutation ignoreResults {...opts} mutation={document}>
+            {/* @ts-expect-error */}
```
Comment (phryneas) [inline src/react/hoc/mutation-hoc.tsx:89]: not gonna fix types in the old HOCs...

File: src/react/hooks/useMutation.ts [hunk 4]
```diff
@@ -102,7 +103,10 @@ export function useMutation<
             executeOptions.onError || ref.current.options?.onError;
 
           if (error && onError) {
-            onError(error, clientOptions);
+            onError(
+              error,
+              clientOptions as MutationOptions<TData, OperationVariables>
+            );
```
Comment (phryneas) [inline src/react/hooks/useMutation.ts:109]: We might want to look closer into these, but for now I'm just casting them around..

**Comment by phryneas** [comment]
This is ready for review now.

**Comment by phryneas** [comment]
Forget about that, I was just calling `yarn tsc` locally, which didn't typecheck the tests 😮‍💨

File: src/utilities/common/__tests__/mergeDeep.ts [hunk 5]
```diff
@@ -146,7 +146,7 @@ describe("mergeDeep", function () {
   });
 
   it("supports custom reconciler functions", function () {
-    const merger = new DeepMerger((target, source, key) => {
+    const merger = new DeepMerger(function (target, source, key) {
```
Comment (phryneas) [inline src/utilities/common/__tests__/mergeDeep.ts:149]: I'm a bit puzzled that this test worked... maybe that test needs deeper recursion?

File: src/core/ObservableQuery.ts [hunk 6]
```diff
@@ -928,7 +928,9 @@ Did you mean to call refetch(variables) instead of refetch({ variables })?`,
     newOptions?: Partial<WatchQueryOptions<TVariables, TData>>,
     newNetworkStatus?: NetworkStatus
   ) {
-    return this.reobserveAsConcast(newOptions, newNetworkStatus).promise;
+    return this.reobserveAsConcast(newOptions, newNetworkStatus).promise.then(
+      ensureResult
+    );
```
[the remark this answers is not in the document]
Comment (phryneas) [reply src/core/ObservableQuery.ts:933]: This seems to trip up a bunch of tests - I'll look into moving that into a separate test tomorrow.

File: src/utilities/types/TODO.ts [hunk 7]
```diff
@@ -0,0 +1,2 @@
+/** @internal */
+export type TODO = any;
```
Comment (phryneas) [inline src/utilities/types/TODO.ts:2]: I added this type for `any`-casts we want to remove in the future (e.g. in a separate PR, like in this case). As it is imported everywhere, we can easily use TS to track all of it's usages down and eliminate them.

**Comment by phryneas** [comment]
The base for this PR is now the Api-Extractor branch, so this PR can be reviewed, but not be merged before that other branch is merged.

File: .api-reports/api-report.md [hunk 8]
```diff
@@ -398,7 +398,7 @@ namespace Cache_2 {
     // (undocumented)
     interface BatchOptions<TCache extends ApolloCache<any>, TUpdateResult = void> {
         // (undocumented)
-        onWatchUpdated?: (this: TCache, watch: Cache_2.WatchOptions, diff: Cache_2.DiffResult<any>, lastDiff: Cache_2.DiffResult<any> | undefined) => any;
+        onWatchUpdated?: (this: TCache, watch: Cache_2.WatchOptions, diff: Cache_2.DiffResult<any>, lastDiff?: Cache_2.DiffResult<any> | undefined) => any;
```
Comment (phryneas) [inline .api-reports/api-report.md:401]: This file sums up all the relevant changes to our external api. (The main entrypoint, that is)

**Review by phryneas — APPROVED** [review]
I've given this yet another full review, and I approve. @jerelmiller, please also give this another pass - and then let's get this in as soon as possible!

File: src/utilities/types/TODO.ts (hunk 7 above)
Comment (jerelmiller) [reply src/utilities/types/TODO.ts:2]: Love it!

File: src/cache/inmemory/fragmentRegistry.ts [hunk 9]
```diff
@@ -29,24 +30,22 @@ export function createFragmentRegistry(
...
-      this.register.apply(this, fragments);
+      this.register(...fragments);
     }
   }
 
-  public register(): this {
+  public register(...fragments: DocumentNode[]): this {
     const definitions = new Map<string, FragmentDefinitionNode>();
-    arrayLikeForEach.call(arguments, (doc: DocumentNode) => {
+    fragments.forEach((doc: DocumentNode) => {
```
[the remark this answers is not in the document]
Comment (jerelmiller) [reply src/cache/inmemory/fragmentRegistry.ts:48]: I'm ok with it.
