### PR TITLE
Normalize user-provided HttpLink headers by lower-casing their names.

### LINKED ISSUE #8447: Request headers are duplicated if letter casing is not matched
Apollo sets default headers such as `content-type` and `accept`. It doesn't handle case insensitivity if a developer tries to override these headers.

**Intended outcome:**

Given:
```ts
const client = new ApolloClient({
    uri: GRAPHQL_URI,
    cache: new InMemoryCache(),
    link: createHttpLink({
        uri: GRAPHQL_URI,
        headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json',
        },
    }),
})
```

I would expect the request headers to be set accordingly

**Actual outcome:**
Request headers are set as:

```
accept: */*, application/json
content-type: application/json, application/json
```

I believe it is related to case (in)sensitivity as It is possible to correct this by matching Apollo's default causing, e.g.:
```ts
        headers: {
            accept: 'application/json',
            'content-type': 'application/json',
        },
```
**How to reproduce the issue:**

**Versions**
```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 88.0
    Safari: 14.1.1
  npmPackages:
    @apollo/client: ^3.3.20 => 3.3.20 
```

### PR DESCRIPTION
**Pull request by benjamn**
Should fix #8447, by preferring the _last_ (according to `Object.keys(headers)`) header among multiple headers whose names are case-insensitively equivalent.

I'm a little worried this could be a user-visible change in some (HTTP-specification-violating) situations. If so, we can easily retarget this PR to the `release-3.4` branch, and make a clear note of it in `CHANGELOG.md`.

### CODE REVIEW

**Review by brainkim — APPROVED** [review]

**Comment by brainkim** [comment]
lgtm

**Review by umpox — APPROVED** [review]

File: src/link/http/selectHttpOptionsAndBody.ts [hunk 1]
```diff
@@ -147,3 +147,16 @@ export const selectHttpOptionsAndBody = (
     body,
   };
 };
+
+function headersToLowerCase(
+  headers: Record<string, string> | undefined
+): typeof headers {
+  if (headers) {
+    const normalized = Object.create(null);
+    Object.keys(Object(headers)).forEach(name => {
```
Comment (v1adko) [inline src/link/http/selectHttpOptionsAndBody.ts:156]: I wonder why you chose the forEach approach instead of `return reduce`. In this day and age, everyone is liking their immutability very much, even in such trivial cases. Is it just preference?
