### PR TITLE
Ignore TypedArrays when freezing object

### LINKED ISSUE #6813: Cache and Typed arrays
**Intended outcome:**
When trying to pass `TypedArray`s as a local-only field it should work

**Actual outcome:**
Apollo throws `Cannot freeze array buffer views with elements`

**How to reproduce the issue:**
Pass a non empty `TypedArray` to a local-only field.

### PR DESCRIPTION
**Pull request by geekuillaume**
### Checklist:

- [x] Make sure all of the significant new logic is covered by tests

This PR fixes #6813 by ignored TypedArrays when freezing objects.

### CODE REVIEW

File: src/utilities/common/__tests__/maybeDeepFeeze.ts [hunk 1]
```diff
@@ -14,4 +14,9 @@ describe('maybeDeepFreeze', () => {
     maybeDeepFreeze(foo);
     expect(() => (foo.bar = 1)).toThrow();
   });
+
+  it('should freeze a TypedArray', () => {
```
Comment (brainkim) [inline src/utilities/common/__tests__/maybeDeepFeeze.ts:18]: little nit, the name of this test should be `should not freeze` right?

Comment (brainkim) [reply src/utilities/common/__tests__/maybeDeepFeeze.ts:18]: Or maybe `should freeze a TypedArray without throwing` perhaps

**Comment by brainkim** [comment]
@benjamn This looks good to me! Though perhaps you have a more comprehensive solution including more edge cases.

File: src/utilities/common/__tests__/maybeDeepFeeze.ts (hunk 1 above)
Comment (geekuillaume) [reply src/utilities/common/__tests__/maybeDeepFeeze.ts:18]: `should ignore a TypedArray when freezing`?

**Comment by benjamn** [comment]
@geekuillaume @brainkim I agree we should err on the side of silencing all possible `TypeError`s, since there are a handful of other types that cause a `TypeError` when passed to `Object.freeze` (and more could be added to the language or to host environments like Node.js in the future). See https://github.com/apollographql/apollo-client/pull/8813/commits/87f604eef92f956f9210f34cd898a0ef37c8f824 for my take!

**Review by benjamn — APPROVED** [review]
Thanks for getting this started @geekuillaume! Since I assigned #6813 to myself, you technically did (most of) my job for me—much appreciated.
