### PR TITLE
Fix RxJS interop issue with observable returned in `WebSocketLink`

### LINKED ISSUE #13186: Subscriptions using subscriptions-transport-ws are broken
### Issue Description

It looks like the subscribe call isn't propagated to the SubscriptionClient and thus no actual subscription is sent to the server.

### Link to Reproduction

https://github.com/simhnna/apollo-subscription-issue

### Reproduction Steps

Start server.js and client -> not working

start server-ws.js and client-ws -> working (using graphql-ws)

### `@apollo/client` version

4.1.6

### PR DESCRIPTION
**Pull request by jerelmiller**
Closes #13186

The observable returned from `WebSocketLink` is a [hand-written observable](https://github.com/apollographql/subscriptions-transport-ws/blob/36f3f6f780acc1a458b768db13fd39c65e5e6518/src/client.ts#L196-L232) (since it just forwards the observable returned by the client) which is incompatible with RxJS. `QueryManager` uses `.pipe` on the returned observable which is currently throwing an error since `.pipe` doesn't exist on the `WebSocketLink` observable.

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed WebSocket observable handling to ensure proper subscription cleanup and improved RxJS interoperability.
* **Tests**
  * Updated tests to align with the revised observable behavior.
* **Chore**
  * Published a patch update for the client package.

### CODE REVIEW

File: src/link/ws/__tests__/webSocketLink.ts
Comment (jerelmiller) [inline src/link/ws/__tests__/webSocketLink.ts:1]: I didn't add additional tests. These tests all use a mock client, which uses RxJS observables and using the real client expects a real websocket connection. I'd have to build a mock websocket implementation to avoid hitting the network.

This link is deprecated anyways and I've confirmed the fix with the original reproduction.

File: src/link/ws/index.ts [hunk 1]
```diff
@@ -115,8 +115,14 @@ export class WebSocketLink extends ApolloLink {
   public request(
     operation: ApolloLink.Operation
   ): Observable<ApolloLink.Result> {
-    return this.subscriptionClient.request(
-      operation
-    ) as Observable<ApolloLink.Result>;
+    return new Observable((observer) => {
```
Comment (phryneas) [inline src/link/ws/index.ts:118]: I was hoping we could use `from` here, but `subscriptions-transport-ws` seems to be so old it doesn't even have `Symbol.observable` :(

**Review by phryneas — APPROVED** [review]
LGTM
