### PR TITLE
fix: strengthen MockedResponse.newData type (#11584)

### LINKED ISSUE #11584: Better types MockedResponse.newData
Sorry for the blank issue & run, but I don't have time to make this a PR for next couple of weeks, but didn't want it to get forgotten:

https://github.com/apollographql/apollo-client/blob/65ab695470741e8dcaef1ebd7742c3c397526354/src/testing/core/mocking/mockLink.ts#L38C28-L38C39

should be: `newData?: ResultFunction<FetchResult<TData>, TVariables>;` 

So the `newData` function is properly typed 🙏

### PR DESCRIPTION
**Pull request by Stephen2**
### Checklist:
- [x] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

Closes #11584

### CODE REVIEW

File: src/testing/core/mocking/__tests__/mockLink.ts [hunk 1]
```diff
@@ -1,7 +1,55 @@
...
+  }
+});
+
+// @ts-expect-error destructing input variables that don't exist in TVariables should fail
+passingTestForNewData.newData = ({ fake: { faker } }) => ({
+  data: {
+    a: faker
+  }
+});
+
```
Comment (jerelmiller) [inline src/testing/core/mocking/__tests__/mockLink.ts:52]: Rather than putting this in the global scope, could you put this into a `describe`/`it` block? Its helpful to see these are in the test runner output. I know it doesn't make a ton of difference in terms of how it succeeds/fails the tests, but its easy to miss these are meant to be type tests otherwise. Doing this also means you can provide a description of the intended behavior which is helpful documentation 🙂 

You can see some examples of how we do this already in a test such as [`useLoadableQuery`](https://github.com/apollographql/apollo-client/blob/ac4ae8498cf8bf63b21dc5886d942976c7dc0eaa/src/react/hooks/__tests__/useLoadableQuery.test.tsx#L4648-L4649).

We are evaluating [`attest`](https://github.com/arktypeio/arktype/tree/beta/ark/attest#readme) at the moment for these types of type tests which will need the `it`/`test` syntax eventually anyways 🙂 (I know its impossible for you to know that, just pointing out why its beneficial to move it into its own test block).

File: src/testing/core/mocking/__tests__/mockLink.ts [hunk 2]
```diff
@@ -1,7 +1,55 @@
...
+    },
+  }),
+}
+
+// @ts-expect-error 'data' still has to be an object
+passingTesForNewDataUntypedMockedResponse.newData = () => ({
+  data: "123",
+});
+
+// Strongly typed MockedResponse is much more developer friendly
```
Comment (jerelmiller) [inline src/testing/core/mocking/__tests__/mockLink.ts:26]: This is technically true of any type, so I'm not sure this comment is super helpful. I like how your other cases describe the intended behavior, so how about something like:

```suggestion
// Requires output type to match query type
```

Besides, I think this would make a better `test(...)` description anyways. See my other comment on converting these to use the `test`/`it` syntax.

File: src/testing/core/mocking/__tests__/mockLink.ts [hunk 3]
```diff
@@ -1,7 +1,55 @@
...
+  },
+
+  newData: ({ input }) => ({
+    data: {
+      a: input
+    }
+  })
+};
+
+// @ts-expect-error returning output that doesn't match TData should fail
```
Comment (jerelmiller) [inline src/testing/core/mocking/__tests__/mockLink.ts:39]:
```suggestion
// @ts-expect-error returns output that doesn't match TData
```

I think the `@ts-expect-error` is a good indicator we expect this to fail, so the "should fail" feels a bit redundant here 🙂

File: src/testing/core/mocking/__tests__/mockLink.ts [hunk 4]
```diff
@@ -1,7 +1,55 @@
...
+passingTestForNewData.newData = () => ({
+  data: {
+    a: 123
+  }
+});
+
+// @ts-expect-error destructing input variables that don't exist in TVariables should fail
```
Comment (jerelmiller) [inline src/testing/core/mocking/__tests__/mockLink.ts:46]:
```suggestion
// @ts-expect-error using input variables that don't exist in TVariables
```

File: .changeset/dirty-insects-return.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+"@apollo/client": patch
+---
+
+Strengthen MockedResponse.newData type
```
Comment (jerelmiller) [inline .changeset/dirty-insects-return.md:5]:
```suggestion
Strengthen `MockedResponse.newData` type
```

This is so minor I almost didn't add this, but its nice to see at a glance the parts that refer to code 🙈

**Review by jerelmiller — CHANGES_REQUESTED** [review]
Hey @Stephen2 👋 

Thanks so much for this contribution! This is super helpful and I'm honestly surprised we didn't do this sooner. I just had a few comments for you in regards to structuring the tests that I'd like to see changed, but otherwise I'd love to get this in the next patch. Thanks a bunch!

**Comment by jerelmiller** [comment]
@Stephen2 for the CircleCI Pipeline, I _think_ you have to login there for those checks to run. Would you mind trying that?

**Comment by Stephen2** [comment]
> @Stephen2 for the CircleCI Pipeline, I _think_ you have to login there for those checks to run. Would you mind trying that?

Just did this, created new account, signed in, but still wouldn't let me rerun this pipeline

File: src/testing/core/mocking/__tests__/mockLink.ts (hunk 4 above)
Comment (Stephen2) [reply src/testing/core/mocking/__tests__/mockLink.ts:46]: done

File: .changeset/dirty-insects-return.md (hunk 5 above)
Comment (Stephen2) [reply .changeset/dirty-insects-return.md:5]: done

File: src/testing/core/mocking/__tests__/mockLink.ts (hunk 3 above)
Comment (Stephen2) [reply src/testing/core/mocking/__tests__/mockLink.ts:39]: done

File: src/testing/core/mocking/__tests__/mockLink.ts (hunk 2 above)
Comment (Stephen2) [reply src/testing/core/mocking/__tests__/mockLink.ts:26]: done

File: src/testing/core/mocking/__tests__/mockLink.ts (hunk 1 above)
Comment (Stephen2) [reply src/testing/core/mocking/__tests__/mockLink.ts]: done

**Comment by Stephen2** [comment]
Took some liberties with your comments, but I think I captured the intention. Check it out again, ready for re-review

File: src/testing/core/mocking/__tests__/mockLink.ts [hunk 6]
```diff
@@ -1,7 +1,62 @@
...
+        },
+      }),
+    }
+
+    test("returned 'data' still has to be an object", () => {
+      // @ts-expect-error
+      passingTestForNewData.newData = () => ({
+        data: "123",
+      });
+    });
```
[the remark this answers is not in the document]
Comment (Stephen2) [reply src/testing/core/mocking/__tests__/mockLink.ts]: I love that article, and have read it & referenced it to others many times 👍 

I've taken 1 more attempt at formatting this how your repo would like, except using a `setup` function, like the article suggests.

Let me know if it's still off base, and I'll remove it, and place the initialization inside each individual test case, as you'd like.

**Comment by Stephen2** [comment]
> Just to double check, is the email address you're using here on GitHub the same as CircleCI?
Yeah, it definitely is.

**Comment by jerelmiller** [comment]
I'll try pushing a tiny edit to this branch and see if perhaps that will kick it off? So sorry for the inconvenience here!

**Review by jerelmiller — APPROVED** [review]
The `setup` function still feels a tad overabstracted, but I can live with it. Thanks for making these updates! Don't worry about the extract API task failing. I'll get a commit pushed up to make this pass 🙂

**Comment by jerelmiller** [comment]
@Stephen2 would you mind running `npm run format` and pushing that change? I'd be happy to do it if need be, but I'd prefer you get credit for those lines of code written 🙂

**Comment by Stephen2** [comment]
> The `setup` function still feels a tad overabstracted, but I can live with it. Thanks for making these updates! Don't worry about the extract API task failing. I'll get a commit pushed up to make this pass 🙂

Nah it's great, it'll grow on you. xD

You're a good maintainer, I appreciate you.

Hopefully we're ready to squash & merge now, except I think CircleCI needs to be kicked again :(

**Comment by jerelmiller** [comment]
Argh, that darn circle job. I'll get that kicked off again. As soon as thats green, I'm happy to merge this! We'll get this in the next patch release.

And thanks so much for the kind comments 🙂. Means a lot!
