### PR TITLE
Stop feuds by skipping cache writes for unchanged network results.

### LINKED ISSUE #6307: Fetching data again and again if more queries without id executed
The problem started after upgrading from beta 45 to beta 48 and is related to missing `id` in queries. 

**Intended outcome:**
I have two components, displaying a list of items, each has its own query. The queries are very similar and differ only in query arguments.

```tsx
function MyRecentIncidents() {
  const {loading, error, data} = useQuery<MyRecentIncidentsQuery>(MY_RECENT_INCIDENTS);
  console.log('[Query 1] loading:', loading, 'error:', error, 'data:', data);
  return null;
}

const MY_RECENT_INCIDENTS = gql`
  query MyRecentIncidents {
    viewer {
      incidents(first: 5, createdByViewer: true) {
        nodes {
          id
        }
      }
    }
  }
`;

function RecentIncidents() {
  const {loading, error, data} = useQuery<RecentIncidentsQuery>(RECENT_INCIDENTS);
  console.log('[Query 2] loading:', loading, 'error:', error, 'data:', data);
  return null;
}

const RECENT_INCIDENTS = gql`
  query RecentIncidents {
    viewer {
      incidents(first: 5) {
        nodes {
          id
        }
      }
    }
  }
`;

const client = new ApolloClient({
  cache: new InMemoryCache(),
  uri: process.env.REACT_APP_API_GRAPHQL_URL,
});

export default function App() {
  return (
    <ApolloProvider client={client}>
      <MyRecentIncidents/>
      <RecentIncidents/>
    </ApolloProvider>
  );
}

```
It should fetch each query just once, render items and doesn't do anything more.

**Actual outcome:**
After initial queries complete, a new request to the server is started. Once completed, _the other_ query starts. Then the first one. And again and again… 

However, `loading` status doesn't change, the components don't rerender. It just fetches data in the background.

image

**My observations:**
The code above worked in beta 45, the problem occurs in beta 48+. I didn't try 46 and 47. It's still present in the just-released beta 49.

Querying `id` field on `viewer` like

```tsx
const RECENT_INCIDENTS = gql`
  query RecentIncidents {
    viewer {
      id # <--- this fixes it
      incidents(first: 5) {
        nodes {
          id
        }
      }
    }
  }
`;
```
in both queries fixes the problem.

**Versions**
```
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @apollo/client: ^3.0.0-beta.48 => 3.0.0-beta.48 
    @apollo/link-context: ^2.0.0-beta.3 => 2.0.0-beta.3 
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3 
```

### PR DESCRIPTION
**Pull request by benjamn**
Ever since the big refactoring in #6221 made the client more aggressive about triggering network requests in response to incomplete cache data (when using a `FetchPolicy` of `cache-first`), folks testing the betas/RCs have reported that feuding queries can end up triggering an endless loop of unhelpful network requests.

This change does not solve the more general problem of queries competing with each other to update the same data in incompatible ways (see #6372 for other mitigation strategies), but I believe this commit will effectively put a stop to most cases of endless network requests.

See my lengthy implementation comment for more details, since this is a non-obvious solution to a very tricky problem.

Should fix #6307, #6370, #6434, and #6444.

### CODE REVIEW

File: src/core/QueryInfo.ts [hunk 1]
```diff
@@ -218,11 +223,57 @@ export class QueryInfo {
...
+            // data in the meantime, that's too bad, but there will be no
+            // winners if every query blindly reverts to its own version
+            // of the data. This approach also gives the network a chance
+            // to return new data, which will be written into the cache as
+            // usual, notifying only those queries that are directly
+            // affected by the cache updates, as usual. In the future, an
+            // even more sophisticated cache could perhaps prevent or
+            // mitigate the clobbering somehow, but that would make this
+            // particular cache write even less important, and thus
+            // skipping it would be even safer than it is today.
```
Comment (benjamn) [inline src/core/QueryInfo.ts:259]: Just surfacing this implementation comment, since it explains the design space as I understand it.

File: src/core/__tests__/QueryManager/index.ts [hunk 2]
```diff
@@ -2049,19 +2049,6 @@ describe('QueryManager', () => {
...
-              ...data2,
-              author: {
-                ...data2.author,
-                id: data1.author.id,
-              },
-            },
-            loading: false,
-            networkStatus: NetworkStatus.ready,
-          });
-        },
```
Comment (benjamn) [inline src/core/__tests__/QueryManager/index.ts:2064]: This was the only existing test that broke as a result of these changes, and it makes sense that this `result` would no longer be delivered, if you trace the code through. That said, **this PR needs more tests**, since the improved network behavior will be very important to defend/preserve.
