### PR TITLE
fix: Merge mutation variables from base options and function invocation

### LINKED ISSUE #6619: Variables set on mutate function override one set on useMutation hook
**Intended outcome:**

Variables passed to `mutate` function and variables set on `useMutation` merged together into one object

**Actual outcome:**

Variables passed to `mutate` function override what was set on `useMutation`

**How to reproduce the issue:**

```javascript
const [updateThing] = useMutation(UPDATE_THIS_GQL, {
  variables: {
    id: thingId
  }
});

...

const result = await updateThing({
  variables: {
    ...otherValuesButId
  }
});
```

**Versions**

I believe that this was introduced by https://github.com/apollographql/apollo-client/commit/b273d033d6bebddb5fcf4e501e248a0e773e452b, specifically by removing this code:
```javascript
const mutateVariables = Object.assign(
  {},
  variables,
  mutateOptions.variables
);
```

### PR DESCRIPTION
**Pull request by amannn**
### Checklist:

- ~If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)~
- [x] Make sure all of the significant new logic is covered by tests

Fixes #6619

### CODE REVIEW

File: src/utilities/common/compact.ts [hunk 1]
```diff
@@ -1,5 +1,9 @@
 import { TupleToIntersection } from './mergeDeep';
 
+/**
+ * Merges the provided objects shallowly and removes
+ * all properties with an `undefined` value
+ */
```
Comment (amannn) [inline src/utilities/common/compact.ts:6]: I added this comment for clarity.

File: src/react/hoc/__tests__/mutations/index.test.tsx [hunk 2]
```diff
@@ -251,19 +251,11 @@ describe('graphql(mutation)', () => {
...
-          query: queryWithVariables,
-          variables: {
-            second: 2,
-          },
+            second: 2
+          }
         },
         result: { data: expectedData },
-      },
+      }
```
Comment (amannn) [inline src/react/hoc/__tests__/mutations/index.test.tsx:258]: This test actually detected the behaviour for HOCs. Since this is now fixed, I'v adapted the test.

I also added another test specifically for the hooks version.

**Comment by amannn** [comment]
@hwillson would you consider this PR? From the discussion in https://github.com/apollographql/apollo-client/issues/6619 this sounds like it should be fixed, right?

**Comment by hwillson** [comment]
@amannn we're definitely considering this PR, thanks very much for working on it! We'll post back with an update shortly.

**Comment by amannn** [comment]
@hwillson That's great, thanks!

**Review by benjamn — APPROVED** [review]
LGTM with a few changes! Thanks for getting this started, and especially for adding tests, @amannn. These changes will be available to test in the first `@apollo/client@3.3.0` beta release (see #7015).

**Comment by amannn** [comment]
@benjamn Thank you for your help!
