### PR TITLE
Filter `operationType` in payload of `GraphQLWsLink`

### LINKED ISSUE #12946: [4.0] Breaks websocket subscriptions
### Issue Description

I have been using Apollo Client in my react project for a while (version 3.x) and it talks to a Hotcholate GraphQL backend via websockets for subscriptions.

When upgrading to 4.0 I updated our createClient(..) to use the new error functions, everything appeared to be working but I found no websocket subscription works.

When on version 3.x the websocket is established fine and the following are the messages exchanged:
```
{"type":"connection_init"}
{"type":"connection_ack"}
{"id":"f40cbe2b-7b74-4f23-8653-54c016548835","type":"subscribe","payload":{"variables":{},"extensions":{},"operationName":"OnVehicleStatus","query":"subscription OnVehicleStatus {\n  onVehicleStatus {\n    hasLoad\n    motionState\n    timestamp\n    trackingCameraReady\n    rotation {\n      w\n      x\n      y\n      z\n      __typename\n    }\n    translation {\n      x\n      y\n      z\n      __typename\n    }\n    isLocalized\n    speed\n    odometer\n    __typename\n  }\n}"}}
```
When on version 4.0.6 the websocket is established, has these messages exchanged and then gets closed:
```
{"type":"connection_init"}
{"type":"connection_ack"}
{"id":"7e082256-e9b2-4b8a-a1e7-0241bc2fd45f","type":"subscribe","payload":{"query":"subscription OnVehicleStatus {\n  onVehicleStatus {\n    hasLoad\n    motionState\n    timestamp\n    trackingCameraReady\n    rotation {\n      w\n      x\n      y\n      z\n      __typename\n    }\n    translation {\n      x\n      y\n      z\n      __typename\n    }\n    isLocalized\n    speed\n    odometer\n    __typename\n  }\n}","variables":{},"extensions":{},"operationName":"OnVehicleStatus","operationType":"subscription"}}
{"id":"7e082256-e9b2-4b8a-a1e7-0241bc2fd45f","type":"error","payload":[{"message":"Expected a \u0060Colon\u0060-token, but found a \u0060RightBrace\u0060-token.","locations":[{"line":1,"column":443}]}]}
```

note: request headers are identical between 3.x & 4.x

I can put the subscription that is sent over the websocket into the hotchocolate GraphQL UI and it works fine:
```
subscription OnVehicleStatus {
  onVehicleStatus {
    hasLoad
    motionState
    timestamp
    trackingCameraReady
    rotation {
      w
      x
      y
      z
      __typename
    }
    translation {
      x
      y
      z
      __typename
    }
    isLocalized
    speed
    odometer
    __typename
  }
}
```

The only change in the creation of the apollo client between 3.x and 4.x is that for 3.x it sets up an error link:
```
  const errorLink = new ErrorLink(({ graphQLErrors, networkError }) => {
    if (graphQLErrors) {
      if (graphQLErrors.find((e) => e.extensions?.code === 'AUTH_NOT_AUTHORIZED')) {
        window.location.replace('/unauthorized')
        return
      } else if (graphQLErrors.find((e) => e.extensions?.code === 'CLIENT_INPUT_VALIDATION_ERROR')) {
        return new Observable((obs) => {
          obs.error(new ApolloError({ graphQLErrors }))
        })
      } else {
        graphQLErrors.forEach((error) => console.error('[Apollo GraphQL Error]', error))
      }
      return
    }
    if (networkError) {
      console.error('[Apollo Network Error]', networkError)
    }
})
```
and for 4.x it sets up the error link as:
```
const errorLink = new ErrorLink(({ error }) => {
     if (CombinedGraphQLErrors.is(error)) {
      if (error.errors.find((e) => e.extensions?.code === 'AUTH_NOT_AUTHORIZED')) {
        window.location.replace('/unauthorized')
        return
      } else if (error.errors.find((e) => e.extensions?.code === 'CLIENT_INPUT_VALIDATION_ERROR')) {
        return new Observable((obs) => {
          obs.error(error)
        })
      } else {
        error.errors.forEach((error) => console.error('[Apollo GraphQL Error]', error))
      }
      return
    } else if (CombinedProtocolErrors.is(error)) {
      // Handle multipart subscription protocol errors
    } else if (LocalStateError.is(error)) {
      // Handle errors thrown by the `LocalState` class
    } else if (ServerError.is(error)) {
      // Handle server HTTP errors
    } else if (ServerParseError.is(error)) {
      // Handle JSON parse errors
    } else if (UnconventionalError.is(error)) {
      // Handle errors thrown by irregular types
    } else {
      // Handle other errors
    }
    console.error('[Apollo Network Error]', error)
  })
```

### Link to Reproduction

n/a

### Reproduction Steps

_No response_

### `@apollo/client` version

4.0.6

### PR DESCRIPTION
**Pull request by jerelmiller**
Fixes #12946

Removes the `operationType` key in the payload sent by `GraphQLWsLink` which was causing issues with HotChocolate.

### CODE REVIEW

File: src/link/subscriptions/index.ts [hunk 1]
```diff
@@ -79,8 +79,9 @@ export class GraphQLWsLink extends ApolloLink {
     operation: ApolloLink.Operation
   ): Observable<ApolloLink.Result> {
     return new Observable((observer) => {
+      const { operationType, ...request } = operation;
       return this.client.subscribe<ApolloLink.Result>(
-        { ...operation, query: print(operation.query) },
+        { ...request, query: print(operation.query) },
```
Comment (phryneas) [inline src/link/subscriptions/index.ts]: What do you think - should we just be a bit more specific here and only pass in known properties?

```
      const { query, variables, operationName, extensions} = operation;
      return this.client.subscribe<ApolloLink.Result>(
        { variables, operationName, extensions, query: print(query) },
```
