### PR TITLE
Simulate loading result for original query before fetchMore.

### LINKED ISSUE #6354: fetchMore doesn't set loading to true (beta.52)
**Intended outcome:**

When calling `fetchMore`, loading should be set to true.

**Actual outcome:**

It remains false and the data loads without this status ever changing, even though `notifyOnNetworkStatusChange: true` has been set on the `useQuery`

**How to reproduce the issue:**

Nothing special here:

```
const { loading, refetch, fetchMore, error, data } = useQuery(qry, {
    key: dataKey,
    variables,
    partialRefetch,
    notifyOnNetworkStatusChange: true,
    onCompleted: data => {
        if (data[dataKey].totalCount) {
            setTotalCount(data[dataKey].totalCount);
        }
    },
});
const loadMore = React.useCallback(
    (options = {}, loadOnTop = false) =>
        fetchMore({
            updateQuery: (previousResult, { fetchMoreResult, variables }) => {
                onUpdateQuery(loadOnTop);
                [...]
                return {
                    ...first,
                    ...last[dataKey],
                };
            },
            ...options,
        })
            .then(onLoadMore)
            .catch(onLoadMoreError),
    [onLoadMore, onLoadMoreError],
);
```
**Versions**
  Apollo client beta.52
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Safari: 13.1.1

### PR DESCRIPTION
**Pull request by benjamn**
Should fix #6354, #6542, #6534, and #6459.

Reliable delivery of loading results is one of the core benefits that Apollo Client strives to provide, especially since handling loading states tends to be such an annoying, error-prone task in hand-written state management code, and Apollo Client is all about keeping hand-written state management code to a minimum.

Ever since I refactored the `FetchPolicy` system in #6221, the `fetchMore` method of `ObservableQuery` has not been delivering a loading state before sending its request. Instead, the observed query was updated only once, after the completion of the `fetchMore` network request. I've been aware of this problem for a while now, but I procrastinated solving it because I knew it would be, well, annoying. With the final release of AC3 right around the corner (Tuesday!), the time has come to get this right.

This loading result doesn't fit neatly into the `fetchQueryObservable` system introduced by #6221, since the consumer of the loading result is the original `ObservableQuery`, but the network request gets made with a fresh query ID, using different `variables` (and possibly even a different `query`) passed to `fetchMore`. This separation is important so that we don't have to change the `query`/`variables`/`options` of the original `ObservableQuery` for the duration of the `fetchMore` request. Instead, the `fetchMore` request is a one-off, independent request that effectively bypasses the usual `FetchPolicy` system (technically, it always uses the `no-cache` policy).

In Apollo Client 2.x (and before #6221 was released in `beta.46`), this logic was guided by an extra `fetchMoreForQueryId` parameter passed to `QueryManager#fetchQuery`, which ended up appearing in a number (16) of different places, across three different methods of the `QueryManager`. I think it's an improvement that the logic is now confined to one block of code in `ObservableQuery#fetchMore`, which seems naturally responsible for any `fetchMore`-related logic.

Still, I don't love the precedent that this simulated loading state sets, so I hope we can avoid similar hacks in the future.

### CODE REVIEW

File: src/__tests__/fetchMore.ts [hunk 1]
```diff
@@ -990,9 +990,13 @@ describe('fetchMore on an observable query with connection', () => {
...
               break;
             case 1:
+              expect(networkStatus).toBe(NetworkStatus.fetchMore);
+              expect((data as any).entry.comments.length).toBe(10);
+              break;
+            case 2:
               expect(networkStatus).toBe(NetworkStatus.ready);
               expect((data as any).entry.comments.length).toBe(20);
-              resolve();
+              setTimeout(resolve, 10);
```
Comment (benjamn) [inline src/__tests__/fetchMore.ts:999]: These `setTimeout(resolve, 10)` calls don't help the tests pass, but rather give them a chance to fail if they hit the `default` case.

File: src/core/ObservableQuery.ts [hunk 2]
```diff
@@ -305,6 +305,39 @@ export class ObservableQuery<
...
+      // Simulate a loading result for the original query with
+      // networkStatus === NetworkStatus.fetchMore.
+      this.observer.next!({
+        // Note that currentResult is an ApolloCurrentQueryResult<TData>,
+        // whereas this.observer.next expects an ApolloQueryResult<TData>.
+        // Fortunately, ApolloCurrentQueryResult is a subtype of
+        // ApolloQueryResult (with additional .error and .partial fields),
+        // so TypeScript has no problem with this sleight of hand.
+        // TODO Consolidate these two types into a single type (most
+        // likely just ApolloQueryResult) after AC3 is released.
```
Comment (hwillson) [inline src/core/ObservableQuery.ts:334]: I can't wait to see these consolidated!
