### PR TITLE
Fixed single response and added subscriptions to links

### LINKED ISSUE #2022: _this.networkInterface.subscribe is not a function
screenshot from 2017-08-09 14-58-26

### PR DESCRIPTION
**Pull request by evanshauser**
### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

Closes #2022

### CODE REVIEW

File: src/ApolloClient.ts [hunk 1]
```diff
@@ -235,6 +235,18 @@ export default class ApolloClient implements DataProxy {
...
+            next: (data: FetchResult) => handler(data.errors, data.data),
+          });
+          return '';
+        },
+        unsubscribe: (id: string): void => {
+          // wsClient.unsubscribe(id);
+        },
       };
     } else if (
       networkInterface &&
```
Comment (evanshauser) [inline src/ApolloClient.ts]: @jbaxleyiii It would be great to remove the ObservableNetworkInterface here

Comment (jbaxleyiii) [inline src/ApolloClient.ts]: @evanshauser do you think we should remove it before 2.0?

File: src/ApolloClient.ts [hunk 2]
```diff
@@ -235,6 +235,18 @@ export default class ApolloClient implements DataProxy {
...
+          const subscription = (execute(
+            networkInterface as ApolloLink,
+            request,
+          ) as any).subscribe({
+            next: (data: FetchResult) => handler(data.errors, data.data),
+          });
+          return '';
+        },
+        unsubscribe: (id: string): void => {
+          // wsClient.unsubscribe(id);
```
Comment (evanshauser) [inline src/ApolloClient.ts]: Could use a map to keep track of the subscriptions? 2.0 won't have this issue, since the Links will just return an Observable

File: src/ApolloClient.ts (hunk 1 above)
Comment (evanshauser) [inline src/ApolloClient.ts]: @jbaxleyiii Yeah we never published about it and now that subscriptions-transport-ws contains a [request method](https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/client.ts#L164), it breaks subscriptions

CC @DxCx

File: src/ApolloClient.ts [hunk 3]
```diff
@@ -228,25 +234,44 @@ export default class ApolloClient implements DataProxy {
...
+          return id;
+        },
+        unsubscribe: (id: string): void => {
+          if (this.subscriptionMap) {
+            const subscription = this.subscriptionMap.get(id);
+            if (subscription) {
+              subscription.unsubscribe();
+            }
+          }
+        },
```
Comment (DxCx) [inline src/ApolloClient.ts]: if you are still going to override the given apollo-link network interface with an proxy object,
then IMO we should also keep the original request method.
as internals of the client should start using Observables it will be much easier to start coding towards that,
and then later on remove this legacy adapter object and just keep original apollo-link.

**Comment by jbaxleyiii** [comment]
@evanshauser would you be able to resolve these conflicts? I'd love to get a release out to day with these fixes!
