### PR TITLE
Provide more context to `nextFetchPolicy` functions

### LINKED ISSUE #8426: [v3.4 Regression] Changing variables uses nextFetchPolicy instead of fetchPolicy
**Intended outcome:**
I have a query with `fetchPolicy: 'network-only'` and `nextFetchPolicy: 'cache-first'`. When I change the variables, it should fetch new results from the server regardless of what's in the cache.

**Actual outcome:**
Changing the variables appears to use the `nextFetchPolicy` and does not fetch new data from the server.

**How to reproduce the issue:**
https://github.com/dylanwulf/react-apollo-error-template/tree/changing-variables-nextFetchPolicy
Please use branch `changing-variables-nextFetchPolicy`.
Reproduction instructions: Open dev tools and watch the console. Click any of the unselected radio buttons, see that a request to the server is made (this is printed to the console instead of the network tab due to the apollo link). Click "All", see that a request to the server is NOT made.

It looks like this problem first showed up in `v3.4.0-rc.5` and still exists in `v3.4.0-rc.14`

### PR DESCRIPTION
**Pull request by benjamn**
We introduced `options.nextFetchPolicy` in PR #6712 to allow modifying `options.fetchPolicy` after first use, and later made the API more powerful by allowing `nextFetchPolicy` to be a function (PR #6893) which takes the current `fetchPolicy` and dynamically returns a new policy.

This more advanced functional version of `nextFetchPolicy` allows implementing a basic [state machine](https://en.wikipedia.org/wiki/Finite-state_machine) where the various fetch policies (`cache-first`, `network-only`, etc) are the states, and the current `fetchPolicy` is the only input/event provided. When there's only one possible event (that is, the current `fetchPolicy` was just used to fetch the first result), you could argue it doesn't have to be explicitly provided to the state transition function (`nextFetchPolicy`), but then your state machine will probably be pretty limited/boring. Most state machines have several possible inputs/events triggering a variety of transitions between states, and Apollo Client is already starting to need more than one `nextFetchPolicy` event (see #8465).

This PR provides additional _context_ to the `nextFetchPolicy` function as its second parameter (leaving the first parameter untouched for backwards compatibility):
```ts
export interface WatchQueryOptions<TVariables = OperationVariables, TData = any>
  extends Omit<QueryOptions<TVariables, TData>, 'fetchPolicy'> {
  /**
   * Specifies the {@link FetchPolicy} to be used for this query.
   */
  fetchPolicy?: WatchQueryFetchPolicy;
  /**
   * Specifies the {@link FetchPolicy} to be used after this query has completed.
   */
  nextFetchPolicy?: WatchQueryFetchPolicy | ((
    currentFetchPolicy: WatchQueryFetchPolicy,
    context: NextFetchPolicyContext<TData, TVariables>,
  ) => WatchQueryFetchPolicy);
}

export interface NextFetchPolicyContext<TData, TVariables> {
  reason:
    | "after-fetch"
    | "variables-changed";
  observable: ObservableQuery<TData, TVariables>;
  options: WatchQueryOptions<TVariables, TData>;
  initialPolicy: WatchQueryFetchPolicy;
}
```

The `context.reason` can currently be one of the following strings:
* `after-fetch`
  * Triggered after any fetch using the current `options.fetchPolicy`, allowing the usual transition from a network fetch policy like `cache-and-network` or `network-only` to a more cache-friendly policy like `cache-first` or `cache-only`.
* `variables-changed`
  * By default, when variables change, `context.options.fetchPolicy` gets reset to `context.initialPolicy`, as implemented in #8465 to fix #8426. If you provide a `nextFetchPolicy` transition function, you can override this behavior by ignoring the `variables-changed` event.

As a consequence of these changes, one way to make sure `nextFetchPolicy` sticks permanently is to pass a function that _ignores_ the provided `fetchPolicy` and `context` and always returns the same constant value:
```ts
client.watchQuery({
  query,
  fetchPolicy: "cache-and-network",
  nextFetchPolicy: (fetchPolicy, context) => "cache-first",
})
```
This is different from
```ts
client.watchQuery({
  query,
  fetchPolicy: "cache-and-network",
  nextFetchPolicy: "cache-first",
})
```
because the second version allows `options.fetchPolicy` to be reset back to `cache-and-network` when `options.variables` change, whereas the first will continually enforce `cache-first`.

This PR is still a draft because it obviously needs more tests and documentation.

### CODE REVIEW

File: src/core/watchQueryOptions.ts [hunk 1]
```diff
@@ -136,6 +138,14 @@ export interface WatchQueryOptions<TVariables = OperationVariables, TData = any>
   refetchWritePolicy?: RefetchWritePolicy;
 }
 
+export interface NextFetchPolicyContext<TData, TVariables> {
+  reason:
+    | "after-fetch"
+    | "variables-changed"
+  observableQuery: ObservableQuery;
+  options: WatchQueryOptions<TVariables, TData>;
```
Comment (benjamn) [inline src/core/watchQueryOptions.ts:146]: I expect this interface to continue growing as we come up with new `reason`s for applying `nextFetchPolicy` functions, and/or additional contextual information to help `nextFetchPolicy` make good decisions.

File: src/core/ObservableQuery.ts [hunk 2]
```diff
@@ -583,6 +584,44 @@ once, rather than every time you call fetchMore.`);
...
+          reason,
+          options,
+          observableQuery: this,
+        });
+      } else if (reason === "variables-changed") {
+        options.fetchPolicy = this.initialFetchPolicy;
+      } else {
+        options.fetchPolicy = options.nextFetchPolicy;
+      }
+    }
```
Comment (dancrew32) [inline src/core/ObservableQuery.ts:620]: Will this change affect this scenario described [here](https://github.com/apollographql/apollo-client/issues/6760#issuecomment-1028410831)?

Wondering the behavior described in `4` will remain consistent:
> Discovered that setting fetchPolicy in the useQuery hook, would implicitly set nextFetchPolicy with the same policy, but only if there were no defaultOptions set in the ApolloClient instance.

Thanks for your time and confirmation here.

Comment (benjamn) [reply src/core/ObservableQuery.ts:621]: @dancrew32 Since you asked this question, I added some tests to verify the behavior should be the same as before, though it's possible I haven't understood/captured exactly what you mean. The tests exercise `defaultOptions.watchQuery.nextFetchPolicy` in a number of ways, for example. Please take a look at the new tests in `src/core/__tests__/fetchPolicies.ts`, try modifying them if you like, and let us know if anything seems worth adding to improve the test suite.

One difference that might be worth calling out: if (and only if) you were already using a `nextFetchPolicy` _function_ (uncommon, but supported since #6893 or AC v3.2.0), that function will now be called to handle the `variables-changed` event as well as the `after-fetch` event, whereas previously the `fetchPolicy` was reset to its initial value when `variables` changed with no chance to intercept that (possibly unwanted) behavior. I'm mildly concerned this could be a breaking change for existing `nextFetchPolicy` functions that are not prepared to be called in the `variables-changed` case, though I'm hopeful most existing `nextFetchPolicy` functions map their own previous result to itself (so `cache-first` stays `cache-first`).

**Comment by benjamn** [comment]
@hwillson @brainkim I added a number of tests here, so I believe this PR is now ready for review. Docs still to be written.

**Comment by benjamn** [comment]
@StephenBarlow It may be easier to review these docs changes after this PR is merged into `release-3.6`, unless you know off-hand how to enable the Netlify deploy previews for PRs targeting `release-3.6`?

**Review by StephenBarlow — APPROVED** [review]
@benjamn I think this looks good! Any small edits I might make can easily happen after 3.6 lands

File: src/core/ObservableQuery.ts (hunk 2 above)
Comment (dancrew32) [reply src/core/ObservableQuery.ts:621]: My organization has never needed `nextFetchPolicy` in any `useQuery` call sites, so this change shouldn't affect us. I can report back after we upgrade in the future, as I am interested in removing `defaultOptions` overrides in our `ApolloClient` instantiation. Thanks for getting back to me, testing, and documenting all of this.

**Review by dancrew32 — APPROVED** [review]
