### PR TITLE
Replace stray console.debug with invariant.log.

### LINKED ISSUE #7447: console.debug is not a function (react native + react native web)
**Intended outcome:**

Not crash

**Actual outcome:**

Crashes if Apollo Client Developer Tools chrome extension is not installed

Captura de Tela 2020-12-10 às 10 37 55

Even my debug console has console.debug undefined
```
> console.debug
< undefined
```

**How to reproduce the issue:**

1. Disable Apollo Client Developer Tools chrome extension.
2. Run an Expo (SDK 40) Project with @apollo/client
```
$ npm install --global expo-cli

$ expo init my-project
# expo will ask a few things, here you can select javascript and a blank template

$ cd my-project
$ yarn add @apollo/client graphql
$ yarn start
```

3. Try some simple code
```
new ApolloClient({
  uri: 'http://localhost:5000/graphql',
  cache: new InMemoryCache()
});
```

**Versions**

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.198
    Safari: 14.0
  npmPackages:
    @apollo/client: 3.3.4 => 3.3.4
```

### PR DESCRIPTION
**Pull request by benjamn**
Fixes #7447 and #7453, since React Native polyfills the console object without providing a `console.debug` method.

Since this message is promotional, I did not feel comfortable using `invariant.warn`, but our default log level of "warn" would have hidden the message unless [`setLogVerbosity("log")`](https://github.com/apollographql/apollo-client/pull/7226) was called.

Since this is the only use of `invariant.log` in the codebase, I believe it's acceptable to lower the default verbosity level to "log" to allow this particular message to be displayed (otherwise, `invariant.log` messages are effectively useless). You can use `setLogVerbosity("warn")` to exclude these `invariant.log` messages if you like.

### CODE REVIEW

**Comment by benjamn** [comment]
I can confirm that this code displays the message in development if devtools are not installed, and does not display the message after you install the devtools.

File: src/core/ApolloClient.ts [hunk 1]
```diff
@@ -205,26 +205,15 @@ export class ApolloClient<TCacheShape> implements DataProxy {
       if (
         typeof window !== 'undefined' &&
         window.document &&
-        window.top === window.self
+        window.top === window.self &&
+        !(window as any).__APOLLO_DEVTOOLS_GLOBAL_HOOK__ &&
+        window?.navigator?.userAgent?.indexOf('Chrome') > -1
```
Comment (benjamn) [inline src/core/ApolloClient.ts:210]: This line might be a little :suspect:, but undefined is never `>` anything (even `-Infinity`), so it works.

File: src/core/ApolloClient.ts [hunk 2]
```diff
@@ -205,26 +205,15 @@ export class ApolloClient<TCacheShape> implements DataProxy {
...
-            // tslint:disable-next-line
-            console.debug(
-              'Download the Apollo DevTools ' +
-                'for a better development experience: ' +
-                'https://chrome.google.com/webstore/detail/apollo-client-developer-t/jdkknkkbebbapilgoeccciglkfbmbnfm',
-            );
-          }
-        }
+        invariant.log(
+          'Download the Apollo DevTools ' +
```
Comment (jcreighton) [inline src/core/ApolloClient.ts:213]: Should we add in the [Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/apollo-developer-tools/) too?

**Review by jcreighton — APPROVED** [review]

**Comment by krisgardiner** [comment]
Thanks for this @benjamn! 🎉

File: src/core/ApolloClient.ts (hunk 2 above)
Comment (benjamn) [reply src/core/ApolloClient.ts:213]: @jcreighton Sure! What’s the URL we should use for Firefox?

Comment (jcreighton) [reply src/core/ApolloClient.ts:213]: Awesome! This is the Firefox URL: `https://addons.mozilla.org/en-US/firefox/addon/apollo-developer-tools/`
