### PR TITLE
fix `nextFetchPolicy` behaviour with transformed documents

### LINKED ISSUE #11234: Has anything changed with optimisticResponse in > 3.8
I feel like I'm going crazy here. I have optimisticResponse working on `3.7.17` but doesn't work on `3.8`. I can't see anything obvious in the changelog for that version, but ultimately my UI does not update anymore. Unfortunately I tried reproducing in the template repo but I'm not sure it's possible as it doesn't connect to a live GQL API, I tried replay.io but when I press record the browser just crashes :/

What I'm seeing on 3.8 is the mutation works, I see the correct response from the server, the component re-renders, but the old data is prevalent (the change I expect is toggling `completed` to `true` or `false` for a task item.

```javascript
// Mutation in my button component
const toggleTaskCompleted = async () => {
    const newCompleted = !entity.completed;

    if (updateEntity) {
      await updateEntity({
        variables: {
          id: entity.id,
          data: {
            completed: newCompleted,
          },
        },
        optimisticResponse: {
          updateTaskEntity: {
            __typename: entity.__typename,
            id: entity.id,
            completed: newCompleted,
          },
        },
      });
    }
  };
```
And the actual mutation:

```javascript
const [updateEntity] = useMutation(MUTATION, {
    client: window.entitiesClient, // I do this as I have another client due to multiple GQL APIs
  });
```

Removing `optimisticResponse` from the mutation works but with the slow updating UI obviously. The apollo docs don't seem to have changed and the above should work?

Nothing crazy complicated, but just weird that it doesn't update on > 3.8. Apologies I can't give any more than that for now.

### PR DESCRIPTION
**Pull request by phryneas**
Fixes #11234

I adjusted existing tests to catch possible regressions.

### Checklist:

- [x] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

### CODE REVIEW

File: src/core/__tests__/fetchPolicies.ts [hunk 1]
```diff
@@ -814,16 +814,24 @@ describe("cache-and-network", function () {
...
     query EchoQuery {
-      linkCounter
-      opName
-      opVars
+      echo {
+        linkCounter
+        opName
+        opVars
+      }
     }
```
Comment (phryneas) [inline src/core/__tests__/fetchPolicies.ts:835]: Previously, this test did not trigger any query transformation and did not surface this bug.
The additional nesting results in a `__typename` being inserted - and as a result, this test would fail without the fix in this PR.

File: src/core/ObservableQuery.ts [hunk 2]
```diff
@@ -883,20 +885,15 @@ Did you mean to call refetch(variables) instead of refetch({ variables })?`,
       }
     }
 
-    // If the transform doesn't change the document, leave `options` alone and
-    // use the original object.
-    const fetchOptions =
-      query === options.query ? options : { ...options, query };
```
Comment (phryneas) [inline src/core/ObservableQuery.ts:889]: All tests did take the `query === options.query` path here, so this didn't surface.

File: .changeset/early-snakes-cheer.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@apollo/client": patch
+---
+
+keep `options` reference stable when passing it through QueryManager
```
Comment (phryneas) [inline .changeset/early-snakes-cheer.md:5]:
```suggestion
Fix nextFetchPolicy behaviour with transformed documents by keeping `options` reference stable when passing it through QueryManager.
```

**Review by jerelmiller — APPROVED** [review]
Great find on this one! Thanks for fixing 🎉

**Review by alessbell — APPROVED** [review]
