### PR TITLE
Separate error objects

### LINKED ISSUE #12200: [4.0] Separate error objects
Currently we have a single error type `ApolloError` for gathering network errors and GraphQL errors. This class provides separate properties for each: `networkError` and `graphqlErrors` respectively.

## The problem

These errors are mutually exclusive. According to our [docs](https://www.apollographql.com/docs/react/data/error-handling):

> Executing GraphQL operations on a remote server can result in [GraphQL errors](https://www.apollographql.com/docs/react/data/error-handling#graphql-errors) or [network errors](https://www.apollographql.com/docs/react/data/error-handling#network-errors).

The keyword here is _or_. Looking at our [own code base](https://github.com/search?q=repo%3Aapollographql%2Fapollo-client+%22new+ApolloError%22+-path%3A__tests__&type=code), you'll see that in practice, this statement holds true.

The differences in these errors also have implications for how other parts of the library behave when an error is encountered. For example, `useQuery` [always calls `onError`](https://github.com/apollographql/apollo-client/pull/10383/files#diff-d2c5924a921e0cb39c6d9910863c40eaab64a7901aa9414ab702a6eda79f7e82R1904-R1944) for network errors regardless of the error policy. `useSuspenseQuery` will [always throw](https://github.com/apollographql/apollo-client/pull/10401) when a network error is encountered, regardless of the error policy.

By using a single type to model 2 distinct behaviors, this leaves room for impossible states. What happens if both `networkError` and `graphqlErrors` are set? Should `networkError` have priority over `graphqlErrors` because its more unexpected than the other? These properties are meant to be mutually exclusive, so we should model it this way.

## Proposal

Rather than have multiple properties on a single error type, we'd like to split `ApolloError` up into distinct error classes. Doing so allows us to better model the distinction between different error types.

This has positive implications for other types of the code base as well. For example, our [`ApolloQueryResult`](https://github.com/apollographql/apollo-client/blob/bf25da3ade95e58428465ef1da36e466c355f59f/src/core/types.ts#L135) has [2 error properties](https://github.com/apollographql/apollo-client/blob/77b9e0bd1795a111a62f53fb44357cc1fffc242d/src/core/types.ts#L144-L154). This invites confusion as at times its not fully clear which of these properties I as a developer should be using to determine which to look at since [both can be set](https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/useQuery.ts#L575-L581) under certain conditions. 

Because we can treat these errors as mutually exclusive, we can narrow this down to a single `error` property set to the proper error instance.

```tsx
const { error } = useQuery(...);

switch (error.name) {
  // names TBD
  case 'ApolloNetworkError':
    return <div>{error.message}</div>;

  case 'ApolloGraphQLError':
    return (
      <ul>
        {error.messages.map((message) => <li>{message}</li>)
      </ul>
    );
}
```

```ts
const errorLink = onError((error) => {
  // alternate style by checking its instance type
  if (error instanceof ApolloNetworkError) {
    // ...
  } else if (error instanceof ApolloGraphQLError) {
    // ...
  }
});
```

### PR DESCRIPTION
**Pull request by jerelmiller**
Closes #12200

Completely replaces `ApolloError` with separate error types. The error type depends on the type of error encapsulated by `ApolloError`:

### Network errors

Network errors are no longer wrapped by the client and are passed through as-is. This should help prevent issues such as the Kaspersky issue where it looked like Apollo Client was to blame since errors were shown as `ApolloError`.

### GraphQL Errors

These are now encapsulated in a `CombinedGraphQLErrors` type. You can access the original error objects with the `errors` property.

### Protocol errors

Replaced with a `CombinedProtocolErrors` type. You can access the original error objects with the `errors` property.

### Client errors

These weren't really used by the client, so these have no replacement. All non-GraphQL and non-protocol errors are passed through unchanged, so these replace that.

### CODE REVIEW

File: src/__tests__/client.ts [hunk 1]
```diff
@@ -1822,7 +1820,7 @@ describe("client", () => {
 
       await expect(stream).toEmitApolloQueryResult({
         data: undefined,
-        error: new ApolloError({ networkError: new Error("Oops") }),
+        error: new Error("Oops"),
```
Comment (jerelmiller) [inline src/__tests__/client.ts:1823]: This is one of the biggest changes that I'm looking forward to. Raw errors are preserved rather than wrapped. With the recent incident with Kaspersky, I opted to avoid a new wrapping type and instead just pass through the raw error. I think error reporting tools will thank us as well 🙂

File: src/__tests__/client.ts [hunk 2]
```diff
@@ -6111,6 +6105,118 @@ describe("custom document transforms", () => {
...
+  });
+
+  test("wraps unconventional types in UnknownError", async () => {
+    const query = gql`
+      query {
+        hello
+      }
+    `;
+
+    for (const type of [Symbol(), { message: "This is an error" }, ["Error"]]) {
```
Comment (jerelmiller) [inline src/__tests__/client.ts:6170]: I didn't use a `test.each` here because the type of error here is less important than the fact that I'm just trying to use some random things as errors, so there needs to be no distinct error cases for each of these.

File: src/core/QueryInfo.ts [hunk 3]
```diff
@@ -509,20 +508,12 @@ export class QueryInfo {
     return (this.networkStatus = NetworkStatus.ready);
   }
 
-  public markError(error: ApolloError) {
+  public markError(error: Error) {
```
Comment (jerelmiller) [inline src/core/QueryInfo.ts:511]: This argument is removed entirely in https://github.com/apollographql/apollo-client/pull/12397, so I'll make sure this gets updated once that change makes it to the release branch and back through this PR.

File: src/errors/CombinedGraphQLErrors.ts [hunk 4]
```diff
@@ -0,0 +1,28 @@
+import type { GraphQLFormattedError } from "graphql";
+
+export class CombinedGraphQLErrors extends Error {
```
Comment (jerelmiller) [inline src/errors/CombinedGraphQLErrors.ts:3]: Bike shedding welcome

File: src/errors/ServerError.ts [hunk 5]
```diff
@@ -0,0 +1,20 @@
+interface ServerErrorOptions {
+  response: Response;
+  result: Record<string, any> | string;
+}
+
+export class ServerError extends Error {
```
Comment (jerelmiller) [inline src/errors/ServerError.ts:6]: This used to be a type that augmented a plain `Error`, but with the change to network errors that are now passthrough I converted it to a subclass of `Error` so that `instanceof` now works. Same with `ServerParseError`.

File: src/errors/UnknownError.ts [hunk 6]
```diff
@@ -0,0 +1,8 @@
+export class UnknownError extends Error {
```
Comment (jerelmiller) [inline src/errors/UnknownError.ts:1]: Bike shedding welcome. I couldn't come up with a better name, but really this is meant to wrap thrown non-error types (i.e. if you did `throw Symbol()`).

File: src/errors/index.ts [hunk 7]
```diff
@@ -42,99 +25,10 @@ export function graphQLResultHasProtocolErrors<T>(
...
-/**
- * @deprecated This type is deprecated and will be removed in the next major version of Apollo Client.
- * It mistakenly referenced `GraqhQLError` instead of `GraphQLFormattedError`.
- *
- * Use `ReadonlyArray<GraphQLFormattedError>` instead.
- */
-// eslint-disable-next-line @typescript-eslint/no-restricted-types
-export type GraphQLErrors = ReadonlyArray<GraphQLError>;
-
 export type NetworkError = Error | ServerParseError | ServerError | null;
```
Comment (jerelmiller) [inline src/errors/index.ts:28]: I'd be curious your thoughts on whether we should keep this type or not. Looks like its used for the `onError` link for the `networkError` property.

File: src/link/http/parseAndCheckHttpResponse.ts [hunk 8]
```diff
@@ -1,18 +1,12 @@
...
-import { throwServerError } from "../utils/index.js";
-import { PROTOCOL_ERRORS_SYMBOL } from "../../errors/index.js";
+import { PROTOCOL_ERRORS_SYMBOL, ServerError } from "../../errors/index.js";
 import { isApolloPayloadResult } from "../../utilities/common/incrementalResult.js";
 import type { Observer } from "rxjs";
+import { ServerParseError } from "../../errors/ServerParseError.js";
 
 const { hasOwnProperty } = Object.prototype;
 
-export type ServerParseError = Error & {
```
Comment (jerelmiller) [inline src/link/http/parseAndCheckHttpResponse.ts:10]: This is now an error subclass so `instanceof` works 🎉

File: src/react/hooks/__tests__/useLazyQuery.test.tsx [hunk 9]
```diff
@@ -2696,11 +2694,9 @@ describe("useLazyQuery Hook", () => {
 
       expect(result).toEqualQueryResult({
         data: undefined,
-        error: new ApolloError({
-          networkError: new InvariantError(
-            "Store reset while query was in flight (not completed in link chain)"
-          ),
-        }),
+        error: new InvariantError(
```
Comment (jerelmiller) [inline src/react/hooks/__tests__/useLazyQuery.test.tsx:2697]: Should we keep this as an `InvariantError`? Or should we create a separate error class for this?

File: src/react/hooks/__tests__/useMutation.test.tsx [hunk 10]
```diff
@@ -501,9 +510,13 @@ describe("useMutation Hook", () => {
         });
 
         expect(fetchResult.data).toEqual(CREATE_TODO_RESULT);
-        expect(fetchResult.errors[0].message).toEqual(CREATE_TODO_ERROR);
+        // TODO: Unify this with errorPolicy: 'none'
```
Comment (jerelmiller) [inline src/react/hooks/__tests__/useMutation.test.tsx:513]:
```suggestion
```

Turns out this was an issue with that weird `onError` issue with `useMutation` that we are fixing in v4, so this comment is no longer needed. This is actually the correct value.

File: tsconfig.json [hunk 11]
```diff
@@ -16,7 +16,7 @@
     "esModuleInterop": true,
     "experimentalDecorators": true,
     "outDir": "./dist",
-    "lib": ["es2015", "esnext.asynciterable"],
+    "lib": ["es2023", "esnext.asynciterable"],
```
Comment (jerelmiller) [inline tsconfig.json:19]: I went ahead and updated these to es2023 so that we could use the `cause` property with `Error`. Let me know if I should provide a changeset for this or not.

File: src/core/QueryManager.ts [hunk 12]
```diff
@@ -1838,6 +1831,18 @@ export class QueryManager<TStore> {
   }
 }
 
+function maybeWrapError(error: unknown) {
+  if (error instanceof Error) {
+    return error;
+  }
```
Comment (phryneas) [inline src/core/QueryManager.ts:1837]:
```suggestion
interface ErrorLike {
  message: string;
  name: string;
  stack?: string;
}

function isErrorLike(error: unknown): error is ErrorLike {
  return (
    error != null &&
    typeof error === "object" &&
    typeof (error as ErrorLike).message === "string" &&
    typeof (error as ErrorLike).name === "string" &&
    ((error as ErrorLike).stack === undefined ||
      typeof (error as ErrorLike).stack === "string")
  );
}

function maybeWrapError(error: unknown) {
  if (isErrorLike(error)) {
    return error;
  }
```

Comment (phryneas) [reply src/core/QueryManager.ts:1837]: There might be quite a bunch of `Error` classes that don't inherit correctly from `Error` or come from another realm, so I would try to avoid `instanceof Error` here - what about an `ErrorLike` like this?

File: src/errors/CombinedGraphQLErrors.ts (hunk 4 above)
Comment (phryneas) [reply src/errors/CombinedGraphQLErrors.ts:3]: `GraphQLErrorCollection` comes to mind as well, but I don't really care :)

File: src/link/retry/retryLink.ts [hunk 13]
```diff
@@ -68,9 +68,9 @@ class RetryableOperation {
       next: (result) => {
         if (graphQLResultHasProtocolErrors(result)) {
           this.onError(
-            new ApolloError({
-              protocolErrors: result.extensions[PROTOCOL_ERRORS_SYMBOL],
-            })
+            new CombinedProtocolErrors(
+              result.extensions[PROTOCOL_ERRORS_SYMBOL]
+            )
```
Comment (phryneas) [inline src/link/retry/retryLink.ts:73]: Let's move this to the code where `result.extensions[PROTOCOL_ERRORS_SYMBOL]` is initially set, so that `onError` and code in/after `QueryManager` see the same error instance and not two different ones.

File: src/react/internal/cache/QueryReference.ts [hunk 14]
```diff
@@ -513,9 +514,11 @@ export class InternalQueryReference<TData = unknown> {
   private shouldReject(result: ApolloQueryResult<any>) {
     const { errorPolicy } = this.watchQueryOptions;
 
+    // TODO: Determine if we still want the behavior of always rejecting
+    // "network" errors (any error that isn't a CombinedGraphQLErrors).
```
Comment (phryneas) [inline src/react/internal/cache/QueryReference.ts:518]: I would be so happy if we'd change this.

File: src/react/hooks/__tests__/useSuspenseQuery.test.tsx [hunk 15]
```diff
@@ -9363,14 +9344,12 @@ describe("useSuspenseQuery", () => {
...
-              { path: ["hero", "heroFriends", 0, "homeWorld"] }
-            ),
-          ],
-        }),
+        error: new CombinedGraphQLErrors([
+          new GraphQLError(
+            "homeWorld for character with ID 1000 could not be fetched.",
+            { path: ["hero", "heroFriends", 0, "homeWorld"] }
+          ),
+        ]),
```
Comment (phryneas) [inline src/react/hooks/__tests__/useSuspenseQuery.test.tsx:9352]:
```suggestion
        error: new CombinedGraphQLErrors([
          {
            message: "homeWorld for character with ID 1000 could not be fetched.",
            path: ["hero", "heroFriends", 0, "homeWorld"]
          },
        ]),
```

Similar for other places here - these are not `GraphQLError` instances and we should probably not test for that.

File: src/errors/UnknownError.ts [hunk 16]
```diff
@@ -0,0 +1,8 @@
...
+  constructor(errorType: unknown) {
+    super("An error of unknown type occurred", { cause: errorType });
```
[the remark this answers is not in the document]
Comment (jerelmiller) [reply src/errors/UnknownError.ts]: I renamed this to `UnconventionalError` which I think better captures this and updated the error message to your suggestion :) [ff284d1](https://github.com/apollographql/apollo-client/pull/12398/commits/ff284d13cfcb11b5cedbf85164785fc694625aa0)

File: src/link/http/parseAndCheckHttpResponse.ts [hunk 17]
```diff
@@ -145,22 +142,16 @@ function parseJsonBody<T>(response: Response, bodyText: string): T {
         return bodyText;
       }
     };
-    throwServerError(
-      response,
-      getResult(),
-      `Response not successful: Received status code ${response.status}`
+    throw new ServerError(
```
[the remark this answers is not in the document]
Comment (jerelmiller) [reply src/link/http/parseAndCheckHttpResponse.ts:148]: Let's hit this up in a separate PR so we can look at this throughout the client and find other areas where we might be able to optimize.

**Review by phryneas — APPROVED** [review]
A few docblocks, a type change, then it's ready to go :)

File: src/react/hooks/useSuspenseQuery.ts [hunk 18]
```diff
@@ -38,7 +37,7 @@ export interface UseSuspenseQueryResult<
 > {
   client: ApolloClient<any>;
   data: MaybeMasked<TData>;
-  error: ApolloError | undefined;
+  error: Error | undefined;
```
[the remark this answers is not in the document]
Comment (jerelmiller) [reply src/react/hooks/useSuspenseQuery.ts]: Good catch! Looks like `useReadQuery` needed to be updated as well.
