### PR TITLE
WIP: Fragment matcher

### LINKED ISSUE #1337: Schema knowledge needed for fragmentMatcher
Currently, when working with Interfaces/Unions, the fragmentMatcher runs into a problem when trying to detect if a field value is missing (e.g. because the previous query simply didn't include the field) or if the field simply doesn't exist on the type at all. In the latter case, the fragmentMatcher should return ``false``. However, since we don't currently have any knowledge of the types and fields in the schema, we always return ``true`` here as a band-aid solution.

https://github.com/apollographql/apollo-client/blob/master/src/data/readFromStore.ts#L164

**Intended outcome:**
Return ``false`` when a field does not exist on a fragment's type.

**Actual outcome:**
Currently, we always return ``true`` because we simply don't have any knowledge of the types and fields

**How to reproduce the issue:**
Run a query with two fragments with different subselections on a union/interface field. The query will always be re-executed. This is especially annoying when doing SSR. In this case, the client re-runs the queries although it wouldn't be necessary.

**Propose solution**
Add limited knowledge about the schema (available fields on all types) to apollo-client and change the fragmentMatcher accordingly.

### PR DESCRIPTION
**Pull request by helfer**
Fixes #1337 #1363 #1379 #1113 #857 #771 #1297 #1273 #961 #933

Not 100% sure all of these issues will be fixed, but it should fix a good number of them.

TODO:

- [x] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [x] Rebase your changes on master so that they can be merged easily
- [x] Make sure all tests and linter rules pass
- [x] Update CHANGELOG.md with your change
- [x] Add your name and email to the AUTHORS file (optional)
- [ ] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

File: src/core/QueryManager.ts [hunk 1]
```diff
@@ -902,6 +840,109 @@ export class QueryManager {
     };
   }
 
+  // This function runs fetchQuery without initializing the fragment matcher.
+  // We always want to initialize the fragment matcher, so this function should not be accessible outside.
+  // The only place we call this function from is within fetchQuery after initializing the fragment matcher.
+  private fetchQueryWithoutInit<T>(
```
Comment (stubailo) [inline src/core/QueryManager.ts]: I'd call this `fetchQueryAfterFragmentMatcherInit` to be really explicit that you should only call it in that circumstance.

File: src/data/fragmentMatcher.ts [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+  }
+
+
+  public match(idValue: IdValue, typeCondition: string, context: ReadStoreContext) {
+    if (!this.isReady) {
+      // this should basically never happen in proper use.
+      throw new Error('FragmentMatcher.match() was called before FragmentMatcher.init()');
+    }
+
+    // invariant(isIdValue(idValue), 'boo hoo, I am sad');
```
Comment (stubailo) [inline src/data/fragmentMatcher.ts]: Should be deleted

File: src/data/fragmentMatcher.ts [hunk 3]
```diff
@@ -0,0 +1,181 @@
...
+    }
+
+    this.readyPromise = queryManager.query({ query: introspectionQuery })
+    .then( (res: any) => {
+      this.possibleTypesMap = this.parseIntrospectionResult(res.data as IntrospectionResultData);
+      this.isReady = true;
+      return;
+    })
+    .catch( (err: any) => {
+      throw err;
```
Comment (stubailo) [inline src/data/fragmentMatcher.ts]: There's definitely a possibility of a bad outcome here if we couldn't fetch the introspection result. I think a good option could be to set `this.readyPromise = null` so that we try to init again on the next query.

File: src/data/fragmentMatcher.ts [hunk 4]
```diff
@@ -0,0 +1,181 @@
...
+
+    this.init = this.init.bind(this);
+    this.canBypassInit = this.canBypassInit.bind(this);
+    this.match = this.match.bind(this);
+  }
+
+  /**
+   * The init method has to get called before the match function can be used.
+   */
+  public init(queryManager: QueryManager): Promise<void> {
```
Comment (stubailo) [inline src/data/fragmentMatcher.ts]: This is a bit nitpicky, but I think a name like `ensureReady` would be better because that would indicate that this function is called every time, not just once to initialize.

File: src/data/fragmentMatcher.ts [hunk 5]
```diff
@@ -0,0 +1,181 @@
...
+import introspectionQuery from './fragmentMatcherIntrospectionQuery';
+
+import {
+  isTest,
+} from '../util/environment';
+
+export interface FragmentMatcherInstance {
+  canBypassInit: (query: DocumentNode) => boolean;
+  init(queryManager?: QueryManager): Promise<void>;
+  match(idValue: IdValue, typeCondition: string, context: ReadStoreContext): boolean;
```
Comment (stubailo) [inline src/data/fragmentMatcher.ts]: Should this take an `obj` instead of an `idValue`? Seems like both implementations just do `obj = context.store[idValue.id]` as the first statement. I can see that we still want `context` so we can set `returnPartialData`.

File: src/data/fragmentMatcher.ts [hunk 6]
```diff
@@ -0,0 +1,181 @@
...
+import { QueryManager } from '../core/QueryManager';
+import { IdValue, isIdValue } from './storeUtils';
+import { ReadStoreContext } from './readFromStore';
+import introspectionQuery from './fragmentMatcherIntrospectionQuery';
+
+import {
+  isTest,
+} from '../util/environment';
+
+export interface FragmentMatcherInstance {
```
Comment (helfer) [inline src/data/fragmentMatcher.ts]: Yeah, I'll probably go for interface then, because there's already a `FragmentMatcher` in graphql-anywhere, and that one's a function.

File: src/data/fragmentMatcher.ts (hunk 5 above)
Comment (helfer) [inline src/data/fragmentMatcher.ts]: Yeah, I thought about that for a second, but then decided against it, because we might have a store in the future where the typename is stored in the path or in the id, in which case we could theoretically save the lookup. It also saves us from having to update graphql-anywhere or wrapping the fragmentMatcher function before passing it in. I think it's a little bit simpler this way, so we should keep it.

File: src/data/fragmentMatcher.ts (hunk 4 above)
Comment (helfer) [inline src/data/fragmentMatcher.ts]: yup, agreed. The function evolved quite a bit, and it's no longer just an init function.

File: src/data/fragmentMatcher.ts (hunk 3 above)
Comment (helfer) [inline src/data/fragmentMatcher.ts]: Yeah, probably worth a try 👍

File: src/data/fragmentMatcher.ts (hunk 5 above)
Comment (stubailo) [inline src/data/fragmentMatcher.ts]: Sounds good. This is a small enough piece that if we change the store format or anything else later, rewriting this will be the least of our worries.

**Comment by helfer** [comment]
It's worth noting that `client.readFragment` and `client.readQuery` might break if the FragmentMatcher is not initialized. If they are called before the first query returns, the user has to ensure that the fragment matcher has been initialized if it needs to be.

**Comment by stubailo** [comment]
Yeah I guess there's no way to get around that if store reading is synchronous.

**Comment by csillag** [comment]
Hurray!

Where will be the next RC release?

**Comment by helfer** [comment]
@csillag I'll release it in a couple of minutes, but I won't tag it as latest yet, so you'll have to install that specific version or `@next` to get it. 

To use the introspection fragment matcher for now, you'll also need to specifically provide it:

```
import ApolloClient, { IntrospectionFragmentMatcher } from 'apollo-client';

const client = new ApolloClient({
  fragmentMatcher: new IntrospectionFragmentMatcher(),
});
```

I'm doing this because I'd like to make sure that there will not be any unintended consequences of having to fetch (or pre-populate) some schema information before enabling it for everyone by default.

**Comment by csillag** [comment]
Awesome. I will take it for a spin on Monday.

**Comment by helfer** [comment]
cc @fubhy @mdebbar @bgentry @TSMMark @thebigredgeek  I've merged a solution for fragment matching.

It would be great if you could test it by `apollo-client@1.0.0-rc.7` and explicitly using the `IntrospectionFragmentMatcher` as per the instructions above. Once we've confirmed that it works for your apps, we'll flip the switch and roll it out for everyone :tada:

**Comment by bgentry** [comment]
reposting from slack:

@helfer AFAICT the Interface type stuff is fixed :tada:

Unfortunately the upgrade breaks some of my tests around error handling of 4xx server responses. I thought that my observer's `error()` wasn't getting called anymore in that scenario, but it's slightly more complicated than that.

I manipulated a cookie on my app to achieve the same effect outside of tests, and the result is that my actual app is broken by this change.

The reason is due to the fact that this change adds the following introspection query, which runs before any of my app's actual queries:

```graphql
{
  __schema {
    types {
      kind
      name
      possibleTypes {
        name
      }
    }
  }
}
```

My tests assume that the first request that's made is one to load the current user, and the server just always returns a 401 in these tests (as it would IRL when an auth token is invalid for some reason). Thus the introspection query fails on a 401 status.

Likewise, my actual app (outside of tests) tries to load the current user immediately to check if auth is valid, and if not will invalidate the session and cause a login. But my current user query is never even running, presumably due to an error received on this introspection query.

I don't think this is viable because it requires the graphql endpoint to be publicly accessible with no authentication requirement, at least for the sake of this introspection query. My server's graphql endpoint is only available with a valid session, and I don't think that's a use case that can safely be ignored.

**Comment by stubailo** [comment]
@bgentry would adding a build step to inline that type information on startup work for you? Do you have the ability to run introspection locally from your development environment?

**Comment by bgentry** [comment]
Thinking about this some more, I'd of course prefer not to have to make any additional requests when the app loads, especially if it means my app is blocked on another round-trip cycle. Is it possible/easy to use a client-side schema instead of having to make an introspection query on load? Maybe enabling that sort of thing is the purpose of the `FragmentMatcherInterface`.

Also, I'm trying to understand if it's intentional/expected for ApolloClient to fail altogether when the introspection query errors, or if what I'm experiencing is the result of improper error handling in the new fragment matcher.

**Comment by bgentry** [comment]
@stubailo didn't see your comment prior to sending mine. Can you elaborate on what that might look like?

I can certainly run the introspection from a dev environment (assuming that the user is already auth'd), or I can include the raw graphql schema somewhere in the app. I'm concerned about implementing a specialized build pipeline, though, and what it might mean for other users of ember-apollo-client.

**Comment by helfer** [comment]
@bgentry As a workaround you can provide the necessary schema information to the fragment matcher statically. Here's an example:

```

const fm = new IntrospectionFragmentMatcher({
 introspectionQueryResultData: {
  __schema: {
    types: [{
      kind: 'UNION',
      name: 'Item',
      possibleTypes: [{ name: 'GreenItem' }, { name: 'RedItem }]
    }]
  }
});
```

If you do SSR, that query will run on the server and no extra roundtrip will be needed.

It's possible that the error in the fragment matcher currently doesn't bubble up to the user. That should definitely be fixed.

As for authentication, I think that's best handled outside of GraphQL if you're blocking queries entirely if no auth token is present. I agree that if the introspection query fails there should be a way to retry, but I think there are currently enough options to make this viable. You can:

1. Run the introspection query during build time and seed the fragment matcher.
2. Seed the fragment matcher manually in your code
3. Run the introspection query during SSR, in which case no roundtrip will be needed.
4. Allow the introspection query to succeed, even if the user hasn't authenticated yet.
5. Buffer queries until the user is authenticated outside of GraphQL. Might require some modifications to the network interface or some hacks with afterware to retry requests.

Would one of the options above work for you?

**Comment by bgentry** [comment]
1. I'm not sure how I'd fit this into the Ember build pipeline, and it would suck to have to make all users do that.
2. This one seems doable, though annoying to maintain.
3. Not using SSR (fastboot) atm, so not an option.
4. Makes server auth logic quite a bit more complicated as I have to whitelist specific queries to bypass auth.
5. Doesn't actually solve the round-trip latency issue. Also, my current user query *does* user Apollo/GraphQL, so I'd need to move that out in order for this to be viable.

So I guess only #2 (manually seeding the fragment matcher) is an option. That will likely be brittle and hard to maintain, so it's definitely a big step backwards in terms of usability.

I'm also curious if, aside from the immediate workarounds, there are other plans to solve this (perhaps by using the full schema client-side).

**Comment by mdebbar** [comment]
@bgentry actually number 5 could be very simple if you can delay the creation of the Apollo Client until the user is authenticated. In Ember, that could be as simple as making sure that the `apollo` service is only injected in authenticated routes.

**Comment by bgentry** [comment]
@mdebbar I agree that it could be simple to implement what you described, but implementation difficulty was not my issue with #5. It still introduces an extra round trip of latency before my app can start doing real work, *and* it would require me to move away from using Apollo for my `currentUser` query, which is a definite regression.

I don't think that any of the solutions which do this introspection on-the-fly are suitable for real-world production apps, which is why I'm curious if it's merely a temporary stepping stone or if it's intended to be the only option for people that want to use Interfaces or Unions (or even everybody).

I'd much rather embed my whole schema in the frontend app if necessary than deal with a more tangled bootstrapping process or add additional latency cycles on the initial page load.

**Comment by TSMMark** [comment]
Is this supposed to work out of the box? I updated and now getting `GraphQL response missing __typename`

**Comment by helfer** [comment]
@bgentry I don't think there's any way of doing this without schema information. Having schema information requires that you either

A) Include the schema at build time (for example by importing, or by doing an additional build step)
B) Fetch the schema at runtime

For option B importing is only reasonable if your schema is already in JS, which isn't the case for everyone. It would also incur a bundle size penalty. It's pretty easy to implement such a fragment matcher with the interface available today, so if that's the option you want to go for, I'm happy to assist.
Option B could still be optimized such that queries can still be executed without the matcher being ready as long as the matcher isn't needed (store is empty or queries don't contain fragments, etc.). This solution would be quite a bit more complex however, which is why I'd rather not go too far down that path.

One of our most important goals with Apollo is that it works out of the box and doesn't require a build step or tooling for the most common use-cases. 


@bgentry: just so I understand. How is it that your current user query can succeed but not the introspection query? Or are you using the fact that the currentUser query fails to set in motion some kind of login process? If so, could you just use the fact that the introspectionQuery fails for doing the same thing?

**Comment by helfer** [comment]
@TSMMark yes, it should work out of the box. Are you passing `addTypename: false` to Apollo by any chance?

**Comment by TSMMark** [comment]
@helfer I am not. Want me to post the server response for the schema query?

**Comment by stubailo** [comment]
@bgentry how about if you could do option (2), but you had a script that generated the necessary data? So basically:

1. Generate a `.js` file using a very simple script that has the relevant schema information
2. Import that `js` file into your frontend code just like anything else, so it should work fine with the Ember build

In this setup, you would need re-run the script from (1) when you modify the interfaces or unions to your schema.

> I'd much rather embed my whole schema in the frontend app if necessary than deal with a more tangled bootstrapping process

How does this compare to the process above for you?

**Comment by TSMMark** [comment]
Whoops, my bad @helfer. We had a custom `dataIdFromObject` which was throwing that.

```
const dataIdFromObject = (result) => {
  if (!result.__typename) {
    throw 'GraphQL response missing __typename: ' + JSON.stringify(result)
  }
```

I guess `dataIdFromObject` is applied to objects in the response of the schema query too. Intended? Seems a little odd that any part of the schema would need a `dataId`, no?

**Comment by bgentry** [comment]
> I don't think there's any way of doing this without schema information.

Yep, totally get that!

> One of our most important goals with Apollo is that it works out of the box and doesn't require a build step or tooling for the most common use-cases.

I think this is an important goal and it's one that I share.

> @bgentry: just so I understand. How is it that your current user query can succeed but not the introspection query? Or are you using the fact that the currentUser query fails to set in motion some kind of login process? If so, could you just use the fact that the introspectionQuery fails for doing the same thing?

I am using the fact that the `currentUser` query fails (specifically with a 401) to determine that the session should be invalidated. Both the `currentUser` query and the introspection query fail in the same way, however afaict I have no way to know about the failed introspection query. None of my error handlers or promise catches were being called when I tested this out (though I could see that the Apollo query manager was receiving the error, that's as far as I got w/ debugging).

As far as bundling my schema, I am indeed already doing that for usage in my test suite, so it wouldn't be much different to put it in a place where the app itself could use it too.

Since Apollo Client never used the schema before this fragment matcher was added, am I correct to assume that there isn't a documented way to provide a schema? Would I need to implement a custom `FragmentMatcherInterface`, and if so, how much customization would be required? Since I'm sure I won't be the only one needing to do this, it's probably worthwhile to make sure it's easy to do and documented (the latter I can maybe help with).

**Comment by stubailo** [comment]
@bgentry the current design allows you to pass a static object with the data in the constructor: https://github.com/apollographql/apollo-client/pull/1483/files#diff-2223acc12993ca0745c660713b0c4f78R40

**Comment by booboothefool** [comment]
Hi, I arrived at this issue from https://github.com/apollographql/apollo-client/issues/1436 and wanted to try this out. Upgrading from rc.6 to rc.7 and adding: 
```
const client = new ApolloClient({
  ...
  fragmentMatcher: new IntrospectionFragmentMatcher(),
  ...
```
Appears to have broken a few of my initial startup queries (which use fragments).

**Comment by rovansteen** [comment]
It doesn't seem to work for me either. I've added the `IntrospectionFragmentMatcher`, but the data I receive in my component doesn't contain the results from the server anymore.

**Comment by csillag** [comment]
Here are my test results:

### Behavior with 1.0.0-rc.6:

 - loading data with `apollo.query` - :x: data is undefined 
 - loading data with `apollo.watchQuery` - :x: data is undefined
 - loading data with the react wrapper - :white_check_mark:  OK 
 - checking the data after mutation directly in apollo's store - :white_check_mark:  OK
 - checking data after mutation with `apollo.query` - :x: data is still undefined
 - reacting to mutations with `apollo.watchQuery` - :x: no reaction
 - reacting to mutations with the react wrapper - :x: no reaction

### Behavior with 1.0.0-rc.7, with `fragmentMatcher` configured:

 - loading data with `apollo.query` - :white_check_mark:  Works
 - loading data with `apollo.watchQuery` - :white_check_mark:  Works
 - loading data with the react wrapper - :x: Fails
 - checking the data after mutation directly in apollo's store - :white_check_mark:  OK
 - checking data after mutation with `apollo.query` - :white_check_mark: Correct
 - reacting to mutations with `apollo.watchQuery` - :white_check_mark:  Yes!
 - reacting to mutations with the react wrapper - :x: since the react wrapper is defunct, N/A

**Comment by csillag** [comment]
... so, to summarize: `rc.7` it works great, except that (for whatever reason) it totally breaks the React integration, which mostly worked, up to this point, even without `fragmentMatcher`.

**Comment by csillag** [comment]
Further analysis shows that the problem with the React wrapper is caused by the [ObservableQuery.currentResult](http://dev.apollodata.com/core/apollo-client-api.html#ObservableQuery.currentResult) function being broken.

**Comment by csillag** [comment]
> To use the introspection fragment matcher for now, you'll also need to specifically provide it:
> [...]
> I'm doing this because I'd like to make sure that there will not be any unintended consequences of having to fetch (or pre-populate) some schema information before enabling it for everyone by default.

One more bit of info: as far as I can tell, *not* engaging the the `fragmentMatcher` doesn't prevent the regression on `ObservableQuery.currentResult`.

**Comment by helfer** [comment]
Thanks @csillag! That's very interesting, let me look into it.

**Comment by helfer** [comment]
@rovansteen @booboothefool @csillag Could you guys try if your queries work when you pass `{ options: { notifyOnNetworkStatusChange: true } }` to them? That seems to fix the errors I'm seeing in the react-apollo tests.

PS: We recently decided to set the default of `notifyOnNetworkStatusChange` back to `false` because it was causing lots of re-renders for people and it was hard for them to track down the issue.

**Comment by csillag** [comment]
> Could you guys try if your queries work when you pass `{ options: { notifyOnNetworkStatusChange: true } }` to them? 

For me, it doesn't seem to do anything. (`currentResult()` still returns an empty object for `data`.)

However, I can confirm that using `lastResult` instead of `currentResult()` seems to return the desired result.

**Comment by helfer** [comment]
Thanks for the feedback @csillag. Would you be able to make a PR with a failing test or provide a reproduction with react-apollo-error-template?

For me all the tests pass with `currentResult`. Using `getLastResult` breaks a whole bunch of tests, so I think `currentResult` still does something we need...

**Comment by csillag** [comment]
I'll try to do that tomorrow.

FWIW, I didn't use `getLastResult()`; I used `lastResult`.

**Comment by helfer** [comment]
I think `observableQuery.getLastResult()` just returns `observableQuery.lastResult` ;)

**Comment by csillag** [comment]
OK, so I have prepared a reproduction based on `react-apollo-error-template`.

Please test the following two branches:
 - [csillag/use-fragments](https://github.com/csillag/apollo-error-reproduction/tree/csillag/use-fragments) - This one uses rc6. The react wrapper works, but running queries normally does.
 - [csillag/use-fragments-rc7](https://github.com/csillag/apollo-error-reproduction/tree/csillag/use-fragments-rc7) - This one uses rc7 and `fragmentMatcher`. React wrapper doesn't work, but running queries manually does.

### Testing manual query execution

Run this command on the console:
``` JavaScript
apollo.query({query: getPeople}).then(result => console.log(result.data))
```

 * On rc.6, this yields: `Loaded data: undefined`
 * On rc.7, this yields: `Loaded data: Object {people: Array(3), Symbol(id): "ROOT_QUERY"}`

### Testing the React wrapper

The loaded data is automatically displayed on both the browser console and rendered on the UI.

**Comment by rovansteen** [comment]
Any progress on this? I see 1.0 is released but it looks like this bug is still there.

**Comment by csillag** [comment]
Rc.9 works for me flawlessly!

2017. márc. 30. 23:43 ezt írta ("Robert van Steen" <notifications@github.com

**Comment by helfer** [comment]
@rovansteen We didn't make it the default, so you have to specifically pass the fragment matcher and initialize it with the relevant part of your schema:

```
const fm = new IntrospectionFragmentMatcher({
 introspectionQueryResultData: {
  __schema: {
    types: [{
      kind: 'UNION',
      name: 'Item',
      possibleTypes: [{ name: 'GreenItem' }, { name: 'RedItem }]
    }]
  }
});
```

First we also wanted the fragment matcher initialize itself, but the code ended up being more complicated to maintain than we wanted, so we ditched that for now.

We'll try to provide some instructions for how to seed the fragment matcher with a build script or server-side rendering.

**Comment by rovansteen** [comment]
@helfer Is there any clear documentation on this? I can't get it to work. If I don't setup the IntrospectionFragmentMatcher my first result works fine, but if I use the fetchMore method I get no data, even though the server returns the data without any problems. If I do use the fragmentMatcher, I get no data at all for all my queries. I tried it with a partial schema (just the union part) and a complete schema of everything. Both break all my queries.

**Comment by stayclean** [comment]
The problem is solved with the solution, but before we found the solution, 
 [this document](https://www.apollographql.com/docs/react/recipes/fragment-matching.html) which does not work is kind of misleading. Please fix or check the document on the doc website.
