### PR TITLE
Avoid warning about clobbering scalar fields.

### LINKED ISSUE #7071: Merge warnings reported for JSONObject custom scalar
**Intended outcome:**
My understanding is that all scalar values (custom or otherwise) should be treated opaquely and replaced when updating. Such updates should not trigger a data loss merge warning.

**Actual outcome:**
When merging objects containing fields of custom scalar type JSONObject, merge warning are generated in the console for these fields.

**How to reproduce the issue:**
Include [JSONObject custom scalar](https://github.com/Urigo/graphql-scalars) into your schema and resolver map and use it in a type definition

```
scalar JSONObject

type Deployment {
   id: ID!
   state: JSONObject
}
```
execute a query to fetch an object that uses JSONObject, then update the data in the cache so the merge algorithm runs.

```
query DeploymentQuery($id: ID) {
    deployment(id: $id)  {
        id
        state
    }
}
```

Notice that when a deployment object that has a different value for state is being merged, you see warnings in the console about potential data loss for `state` field.

**Versions**
```
  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 79.0
    Safari: 14.0
  npmPackages:
    @apollo/client: ^3.2.0 => 3.2.0
    apollo-angular: ^2.0.3 => 2.0.4
```

### PR DESCRIPTION
**Pull request by benjamn**
While it is possible to write a custom `merge` function that handles updates for scalar field values, we should treat scalar data as opaque by default, without displaying `Cache data may be lost...` warnings (#6372) that nudge the developer to write an unnecessary `merge` function.

In this context, scalar data means any subtree of a `GraphQL` result object for which the corresponding field in the query does not have a selection set. In particular, JSON data may look like any other GraphQL object, but it should be treated as an opaque value if the query does not apply a nested selection set to the field that holds the JSON data.

Should fix #7071.

### CODE REVIEW

File: src/cache/inmemory/writeToStore.ts [hunk 1]
```diff
@@ -284,15 +284,27 @@ export class StoreWriter {
...
 
       if (process.env.NODE_ENV !== "production") {
+        const hasSelectionSet = (storeFieldName: string) =>
+          fieldsWithSelectionSets.has(fieldNameFromStoreName(storeFieldName));
+        const fieldsWithSelectionSets = new Set<string>();
+        workSet.forEach(selection => {
+          if (isField(selection) && selection.selectionSet) {
+            fieldsWithSelectionSets.add(selection.name.value);
+          }
+        });
```
Comment (benjamn) [inline src/cache/inmemory/writeToStore.ts:294]: Because this code is inside of a `process.env.NODE_ENV !== "production"` block, it will not be executed or bundled in production.

**Review by hwillson — APPROVED** [review]
Awesome stuff @benjamn - thanks!
